import assert from 'node:assert/strict';import test from 'node:test';import {historicalClose} from './historical-close.js';
test('historical price reuses the existing public-data key when no dedicated key is configured',async()=>{
 const dedicated=process.env.DATA_GO_KR_STOCK_PRICE_KEY,shared=process.env.DATA_GO_KR_SERVICE_KEY;
 delete process.env.DATA_GO_KR_STOCK_PRICE_KEY;process.env.DATA_GO_KR_SERVICE_KEY='shared-test';
 try{await assert.rejects(historicalClose('005380',new Date('2025-12-31'),async input=>{assert.equal(new URL(String(input)).searchParams.get('serviceKey'),'shared-test');return new Response(JSON.stringify({response:{header:{resultCode:'00'},body:{items:{item:[]}}}}));}),{code:'HISTORICAL_PRICE_NO_DATA'});}
 finally{if(dedicated===undefined)delete process.env.DATA_GO_KR_STOCK_PRICE_KEY;else process.env.DATA_GO_KR_STOCK_PRICE_KEY=dedicated;if(shared===undefined)delete process.env.DATA_GO_KR_SERVICE_KEY;else process.env.DATA_GO_KR_SERVICE_KEY=shared;}
});
test('historical price accepts only exact symbol and prior seven-day window; never future/current fallback',async()=>{const old=process.env.DATA_GO_KR_STOCK_PRICE_KEY;process.env.DATA_GO_KR_STOCK_PRICE_KEY='test';try{let url='';const row=await historicalClose('005380',new Date('2025-12-31'),async input=>{url=String(input);return new Response(JSON.stringify({response:{header:{resultCode:'00'},body:{items:{item:[{srtnCd:'005380',basDt:'20260102',clpr:'999'},{srtnCd:'000001',basDt:'20251231',clpr:'99'},{srtnCd:'005380',basDt:'20251230',clpr:'100'}]}}}}));});assert.equal(row?.value,'100');assert.equal(row?.date,'2025-12-30');assert.ok(url.includes('endBasDt=20260101'));}finally{if(old===undefined)delete process.env.DATA_GO_KR_STOCK_PRICE_KEY;else process.env.DATA_GO_KR_STOCK_PRICE_KEY=old;}});

test('encoded credentials are encoded once; exact filter handles singleton responses',async()=>{const old=process.env.DATA_GO_KR_STOCK_PRICE_KEY;process.env.DATA_GO_KR_STOCK_PRICE_KEY='abc%2B%2F%3D';try{const value=await historicalClose('A005380',new Date('2025-12-31'),async input=>{const u=new URL(String(input));assert.equal(u.searchParams.get('serviceKey'),'abc+/=');assert.equal(u.searchParams.get('likeSrtnCd'),'005380');assert.equal(u.searchParams.has('srtnCd'),false);assert.equal(u.searchParams.get('endBasDt'),'20260101');return Response.json({response:{header:{resultCode:'00'},body:{items:{item:{srtnCd:'005380',basDt:'20251231',clpr:'100'}}}}});});assert.equal(value?.value,'100');assert.equal(value?.date,'2025-12-31');}finally{if(old===undefined)delete process.env.DATA_GO_KR_STOCK_PRICE_KEY;else process.env.DATA_GO_KR_STOCK_PRICE_KEY=old;}});
test('auth XML, call limit, communication and empty result have distinct safe codes',async()=>{const old=process.env.DATA_GO_KR_STOCK_PRICE_KEY;process.env.DATA_GO_KR_STOCK_PRICE_KEY='never-log-this';try{for(const [fetcher,code] of [[async()=>new Response('<OpenAPI_ServiceResponse><returnReasonCode>30</returnReasonCode></OpenAPI_ServiceResponse>'),'HISTORICAL_PRICE_AUTH'],[async()=>Response.json({response:{header:{resultCode:'22'}}}),'HISTORICAL_PRICE_RATE_LIMIT'],[async()=>{throw new Error('secret-url')},'HISTORICAL_PRICE_COMMUNICATION']] as const){await assert.rejects(historicalClose('005380',new Date('2025-12-31'),fetcher),error=>{assert.equal((error as {code:string}).code,code);assert.ok(!String(error).includes('never-log-this'));assert.ok(!String(error).includes('secret-url'));return true;});}}finally{if(old===undefined)delete process.env.DATA_GO_KR_STOCK_PRICE_KEY;else process.env.DATA_GO_KR_STOCK_PRICE_KEY=old;}});
