import {nearestSavedItem} from '../../src/hooks/navigation/pageMemory.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {averageAfter,lotValue,sortStocks,deriveAccountStocks,dayChange} from '../../src/pages/stocks/stockMath.ts';
import type {StockItem} from '../../src/types/models.ts';
const stock=(id:string,per?:number):StockItem=>({id,symbol:id,name:id,listType:'watchlist',currentPrice:519000,priceChangeRate:65000/454000*100,collectionStatus:'success',watchlistItemId:id,per});
test('Lot valuation uses remaining quantity and its own price; missing quote stays unavailable',()=>{assert.deepEqual(lotValue({remainingQuantity:70,buyPrice:230000},519000),{amount:36330000,profit:20230000,rate:(519000/230000-1)*100});assert.ok(Number.isNaN(lotValue({remainingQuantity:70,buyPrice:230000},Number.NaN).amount));assert.equal(Math.round(dayChange(stock('1'))),65000);});
test('buy edit replaces original lot and excludes sold shares, preserving unrounded comparison',()=>{assert.equal(averageAfter(700,230000,70,240000,{remaining:70,price:230000,sold:0}),231000);assert.equal(averageAfter(50,230000,70,240000,{remaining:50,price:230000,sold:20}),240000);assert.equal(averageAfter(700,230000,10,515000),234014.08450704225);});
test('sort keeps missing last in either direction, zero remains valid',()=>{const data=[stock('null'),stock('0',0),stock('2',2)];assert.deepEqual(sortStocks(data,'per',false).map(s=>s.id),['0','2','null']);assert.deepEqual(sortStocks(data,'per',true).map(s=>s.id),['2','0','null']);});
test('selected account holdings override manual category; zero remaining with history is traded and unique',()=>{const history=[{id:'s',type:'SELL',buyTradeId:'b',tradedAt:'2026-09-10T03:00:00Z',security:{id:'1',symbol:'1',name:'1',marketType:'KOSPI'},quantity:'1',unitPrice:'100',amount:'100',realizedProfitLoss:'50',memo:null}] as const;const holdings=[{...stock('1'),listType:'holding' as const,quantity:1}];assert.equal(deriveAccountStocks([stock('1')],holdings,[...history])[0].listType,'holding');const result=deriveAccountStocks([stock('1')],[],[...history]);assert.equal(result.length,1);assert.equal(result[0].listType,'traded');assert.equal(result[0].realizedProfit,50);assert.equal(deriveAccountStocks([stock('1')],[],[])[0].listType,'watchlist');});
test('favorites are the primary ordering and each group keeps user order with missing last',()=>{const data=[stock('null'),stock('0',0),stock('2',2),stock('3',3)];const favorites=new Set(['null','2']);assert.deepEqual(sortStocks(data,'per',false,favorites).map(s=>s.id),['2','null','0','3']);assert.deepEqual(sortStocks(data,'per',true,favorites).map(s=>s.id),['2','null','3','0']);assert.deepEqual(sortStocks(data,'name',true,favorites).map(s=>s.id),['null','2','3','0']);});

test('removed scroll anchors restore to the next surviving item, then the previous or numeric fallback',()=>{const order=['a','b','c','d'];assert.equal(nearestSavedItem('b',order,['a','b','d']),'b');assert.equal(nearestSavedItem('b',order,['a','d']),'d');assert.equal(nearestSavedItem('d',order,['a','b']),'b');assert.equal(nearestSavedItem('b',order,[]),undefined);});
