import test from 'node:test';import assert from 'node:assert/strict';
import {prisma as db} from '../src/lib/prisma.js';import {buildApp} from '../src/app.js';import {storeShareCounts} from '../src/collector/share-counts.js';import {supplementStoredPeriod,supplementSafely} from '../src/collector/valuation-supplement.js';
const url=new URL(process.env.DATABASE_URL??'');if(!['127.0.0.1','localhost'].includes(url.hostname)||!url.pathname.endsWith('_phase16_test'))throw Error('Isolated test DB required');
test('MariaDB shares persist exact receipt/kind with zero, null preservation, corrections and SUCCESS supplementation',async()=>{
 const security=await db.security.create({data:{symbol:'TEST'+Date.now(),name:'주식수검사',marketType:'KOSPI'}}),app=buildApp();
 try{
  const f=await db.dartFinancialFiling.create({data:{securityId:security.id,fiscalYear:2025,periodType:'ANNUAL',reportCode:'11011',fsDivision:'CFS',receiptNo:'99999999999981',reportName:'test',receiptDate:new Date('2026-03-10'),periodEndDate:new Date('2025-12-31'),collectedAt:new Date(),source:'OPEN_DART'}});
  const shares={receiptNo:f.receiptNo,collectedAt:new Date().toISOString(),outstanding:'5827808935',preferred:true,issuedShares:'5919637922',treasuryShares:'91828987',rows:[{stockKind:'보통주',shareClass:'COMMON',issuedShares:'5919637922',treasuryShares:'91828987',outstandingShares:'5827808935',periodEndDate:'2025-12-31'},{stockKind:'우선주',shareClass:'PREFERRED',issuedShares:'100',treasuryShares:'0',outstandingShares:'100',periodEndDate:'2025-12-31'}]};
  await storeShareCounts(db,f,shares);await storeShareCounts(db,f,shares);assert.equal(await db.dartShareSnapshot.count({where:{securityId:security.id}}),2);
  await storeShareCounts(db,f,{...shares,rows:[{...shares.rows[0]!,treasuryShares:null}]});assert.equal((await db.dartShareSnapshot.findFirstOrThrow({where:{securityId:security.id,shareClass:'COMMON'}})).treasuryShares!.toString(),'91828987');
  const res=(await app.inject(`/api/value-analysis/${security.id}?year=2025`)).json().data;assert.equal(res.issuedShares,'5919637922');assert.equal(res.treasuryShares,'91828987');assert.equal(res.outstandingShares,'5827808935');assert.equal(res.shareBasis.receiptNo,f.receiptNo);
  const preferred=(await app.inject(`/api/value-analysis/${security.id}?year=2025&shareClass=PREFERRED`)).json().data;assert.equal(preferred.issuedShares,'100');assert.equal(preferred.treasuryShares,'0');assert.equal(preferred.shareBasis.stockKind,'우선주');
  const semi=await db.dartFinancialFiling.create({data:{securityId:security.id,fiscalYear:2026,periodType:'Q2',reportCode:'11012',fsDivision:'CFS',receiptNo:'99999999999983',reportName:'semiannual',receiptDate:new Date('2026-08-14'),periodEndDate:new Date('2026-06-30'),collectedAt:new Date(),source:'OPEN_DART'}});
  await storeShareCounts(db,semi,{...shares,receiptNo:semi.receiptNo,rows:[{stockKind:'보통주',shareClass:'COMMON',issuedShares:'5846278608',treasuryShares:'82086705',outstandingShares:'5764191903',periodEndDate:'2026-06-30'}]});
  const current=(await app.inject(`/api/value-analysis/${security.id}?year=2026`)).json().data;assert.equal(current.issuedShares,'5846278608');assert.equal(current.treasuryShares,'82086705');assert.equal(current.outstandingShares,'5764191903');assert.equal(BigInt(current.issuedShares)-BigInt(current.treasuryShares),BigInt(current.outstandingShares));
  const where={securityId_fiscalYear_periodType:{securityId:security.id,fiscalYear:2025,periodType:'ANNUAL'}};
  const values={eps:'7',bps:'8',per:'9',pbr:'10',roe:'11'};await db.periodValuation.create({data:{securityId:security.id,fiscalYear:2025,periodType:'ANNUAL',status:'SUCCESS',values,provenance:{receiptNo:f.receiptNo},reasons:{},supplemental:{shares:{outstanding:'5827808935',preferred:true,receiptNo:f.receiptNo}}}});
  let calls=0;await supplementStoredPeriod(db,security.id,2025,'ANNUAL',{load:async(_f,saved,sharesOnly)=>{assert.equal(sharesOnly,true);calls++;return {...saved,shares};}});assert.equal(calls,1);assert.deepEqual((await db.periodValuation.findUniqueOrThrow({where})).values,values);
  await supplementStoredPeriod(db,security.id,2025,'ANNUAL',{load:async()=>{throw Error('cache must avoid recollection');}});
  const corrected=await db.dartFinancialFiling.create({data:{securityId:security.id,fiscalYear:2025,periodType:'ANNUAL',reportCode:'11011',fsDivision:'CFS',receiptNo:'99999999999982',reportName:'correction',receiptDate:new Date('2026-04-10'),periodEndDate:new Date('2025-12-31'),collectedAt:new Date(),source:'OPEN_DART'}});
  assert.equal((await app.inject(`/api/value-analysis/${security.id}?year=2025`)).json().data.issuedShares,null);
  await supplementSafely(db,security.id,2025,'ANNUAL',async()=>{throw Object.assign(Error('safe fixture failure'),{code:'SHARES_ERROR'});});assert.equal((await db.periodValuation.findUniqueOrThrow({where})).status,'SUCCESS');assert.deepEqual((await db.periodValuation.findUniqueOrThrow({where})).values,values);
  await storeShareCounts(db,corrected,{...shares,receiptNo:corrected.receiptNo});assert.equal((await app.inject(`/api/value-analysis/${security.id}?year=2025`)).json().data.shareBasis.receiptNo,corrected.receiptNo);
 }finally{await app.close();await db.dartShareSnapshot.deleteMany({where:{securityId:security.id}});await db.periodValuation.deleteMany({where:{securityId:security.id}});await db.dartFinancialFiling.deleteMany({where:{securityId:security.id}});await db.security.delete({where:{id:security.id}});await db.$disconnect();}
});
