import {Alert,Box,Button,Card,Stack,Typography} from '@mui/material';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useEffect,useRef,useState} from 'react';
import {useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {DateField,FormTextField,NumberField} from '../../components/forms/Fields';
import {PageHeader} from '../../components/navigation/Navigation';
import {useDashboard,useStocks} from '../../hooks/useMockData';
import {useActiveAccount} from '../../hooks/useActiveAccount';
import {createBuyTrade,createSellTrade,getBuyLots,getTradeDetail,updateTrade} from '../../data/roxstockApi';
import {liveApiEnabled} from '../../data/liveData';
import {colors} from '../../styles/tokens';
import {dayChange,averageAfter,won} from '../stocks/stockMath';
import {formatRate,getMarketColor} from '../../utils/format';
import {LegacyTradePage} from './LegacyTradePage';
const kst=(s:string)=>new Date(s).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});
const dateTime=(s:string)=>new Date(s+'T12:00:00+09:00').toISOString();
export function TradePage(){return liveApiEnabled?<StockTradeForm/>:<LegacyTradePage/>;}
export function StockTradeForm(){
 const [params]=useSearchParams(),location=useLocation(),navigate=useNavigate(),client=useQueryClient();const {accountId}=useActiveAccount();
 const type=params.get('type')==='sell'?'sell':'buy',editId=params.get('edit'),stockId=params.get('stock')??'';
 const {data:stocks,isError:stocksError}=useStocks(),{data:dashboard,isError:cashError}=useDashboard();
 const detail=useQuery({queryKey:['tradeDetail',type,editId],enabled:!!editId,queryFn:()=>getTradeDetail(type,editId!)});
 const stock=stocks?.find(s=>s.id===(detail.data?.security.id??stockId));
 const lots=useQuery({queryKey:['allBuyLots',accountId,stock?.id],enabled:!!accountId&&!!stock,queryFn:()=>getBuyLots(accountId!,stock!.id,false)});
 const lot=lots.data?.find(l=>l.id===(type==='sell'?detail.data?.buyTradeId??params.get('lot'):editId));
 const[form,setForm]=useState<{key:string;date:string;quantity:string;price:string;memo:string;fee:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false),saved=useRef(false),quantityRef=useRef<HTMLInputElement>(null),priceRef=useRef<HTMLInputElement>(null),memoRef=useRef<HTMLInputElement>(null),feeRef=useRef<HTMLInputElement>(null);
 const key=`${accountId}:${type}:${editId??stockId}:${params.get('lot')??''}`;
 useEffect(()=>{if(!stock||!accountId||editId&&!detail.data||type==='sell'&&!lot)return;if(form?.key===key)return;const t=detail.data;setForm({key,date:t?kst((type==='sell'?t.soldAt:t.boughtAt)!):new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}),quantity:t?t.quantity:type==='sell'?lot!.remainingQuantity:'',price:t?t.unitPrice:Number.isFinite(stock.currentPrice)?String(stock.currentPrice):'',memo:t?.memo??'',fee:t?.cashTransaction?.feeTaxAmount??'0'});},[accountId,stock,detail.data,lot,key,editId,type,form?.key]);
 const update=(field:'date'|'quantity'|'price'|'memo'|'fee',value:string)=>{if(form)setForm({...form,[field]:value});};
 const q=Number(form?.quantity),p=Number(form?.price),fee=Number(form?.fee??0),amount=q*p;
 const maximum=type==='sell'&&lot?Number(lot.remainingQuantity)+(editId?Number(detail.data?.quantity??0):0):undefined;
 const sold=Number(lot?.soldQuantity??detail.data?.soldQuantity??0);
 const valid=!!form&&form.key===key&&!!accountId&&!!stock&&(!editId||detail.data?.account.id===accountId)&&/^\d{4}-\d{2}-\d{2}$/.test(form.date)&&Number.isFinite(Date.parse(form.date))&&Number.isInteger(q)&&q>0&&Number.isFinite(p)&&p>0&&Number.isFinite(fee)&&fee>=0&&(type!=='sell'||!!lot&&q<=maximum!&&form.date>=kst(lot.boughtAt))&&(type!=='buy'||!editId||!!lot&&q>=sold&&!(lot.sellTrades.some(t=>form.date>kst(t.soldAt))));
 const previous=stock?.averagePrice??0;const after=stock&&form?averageAfter(stock.quantity??0,previous,q,p,editId&&type==='buy'&&lot?{remaining:Number(lot.remainingQuantity),price:Number(lot.unitPrice),sold}:undefined):Number.NaN;
 const cash=dashboard?.summary.cashBalance??Number.NaN,afterCash=editId?cash:cash+(type==='buy'?-amount:amount)-fee,profit=type==='sell'&&lot?q*(p-Number(lot.unitPrice)):Number.NaN;
 const close=()=>location.state?.backgroundLocation?navigate(-1):navigate(params.get('return')==='journal'?`/journal?date=${form?.date??''}`:`/stocks/${stock?.id??stockId}${editId?'?tab=trades':''}`);
 const save=async()=>{if(!valid){if(!Number.isInteger(q)||q<=0||maximum!==undefined&&q>maximum)quantityRef.current?.focus();else if(!Number.isFinite(p)||p<=0)priceRef.current?.focus();return;}if(!form||!stock||lock.current||saved.current)return;lock.current=true;setBusy(true);setError('');try{if(editId){const original=(type==='buy'?detail.data!.boughtAt:detail.data!.soldAt)!;await updateTrade(type,editId,{quantity:form.quantity,unitPrice:form.price,memo:form.memo||null,[type==='buy'?'boughtAt':'soldAt']:form.date===kst(original)?original:dateTime(form.date)});}else if(type==='buy')await createBuyTrade({accountId:accountId!,securityId:stock.id,boughtAt:dateTime(form.date),quantity:form.quantity,unitPrice:form.price,feeTaxAmount:form.fee||'0',memo:form.memo||null});else await createSellTrade({buyTradeId:lot!.id,soldAt:dateTime(form.date),quantity:form.quantity,unitPrice:form.price,feeTaxAmount:form.fee||'0',memo:form.memo||null});saved.current=true;await Promise.all(['stocks','dashboard','buyLots','allBuyLots','stockTrades','journalTrades','targetArrivals','recentBuys','tradeDetail','cashOverview','cashTransactions'].map(key=>client.invalidateQueries({queryKey:[key]})));close();}catch(e){setError(e instanceof Error?e.message:'거래 저장에 실패했습니다.');}finally{setBusy(false);lock.current=false;}};
 if(stocksError&&!stocks||cashError&&!dashboard||detail.isError||lots.isError)return <Alert role="alert" severity="error">거래 정보 조회에 실패했습니다. <Button onClick={()=>{void client.invalidateQueries({queryKey:['stocks']});void client.invalidateQueries({queryKey:['dashboard']});void detail.refetch();void lots.refetch();}}>다시 시도</Button></Alert>;
 if(editId&&detail.data?.account.id!==undefined&&detail.data.account.id!==accountId)return <Alert severity="error">현재 계좌의 거래가 아닙니다.</Alert>;
 if(!form||form.key!==key||!stock)return <Typography role="status">거래 정보를 불러오는 중입니다.</Typography>;
 const field={size:'small' as const,disabled:busy,clearIconSrc:'/stocks-v03/clear.svg',selectOnFocus:true};
 const date=<DateField {...field} calendarIconSrc="/stocks-v03/calendar.svg" autoFocus label={type==='buy'?'매수일자':'매도일자'} value={form.date} onChange={v=>update('date',v)} onEnter={()=>quantityRef.current?.focus()}/>;
 const quantity=<NumberField {...field} label={type==='buy'?'매수수량':'매도수량'} value={form.quantity} onChange={v=>update('quantity',v)} suffix="주" inputRef={quantityRef} onEnter={()=>priceRef.current?.focus()}/>;
 const price=<NumberField {...field} label={type==='buy'?'매수가격':'매도가격'} value={form.price} onChange={v=>update('price',v)} suffix="원" inputRef={priceRef} onEnter={()=>memoRef.current?.focus()}/>;
 return <Stack spacing="8px" data-testid="trade-form" sx={{maxWidth:370,mx:'auto',pb:location.state?.backgroundLocation?0:'80px'}}><PageHeader embedded title={`${type==='buy'?'매수':'매도'} ${editId?'수정':'등록'}`} variant="more" backIcon={<Box component="img" src="/stocks-v03/back.svg" alt=""/>} showAdd={false} onBack={close}/><Card sx={{height:41,p:'4px 8px',borderRadius:'8px',display:'flex',alignItems:'center',justifyContent:'space-between',bgcolor:colors.surface,border:`1px solid ${colors.border}`}}><Box><Typography sx={{fontSize:10,fontWeight:600}}>{stock.name}</Typography><Typography sx={{fontSize:10,color:colors.textMuted}}>{stock.symbol}</Typography></Box><Box sx={{textAlign:'right',color:getMarketColor(stock.priceChangeRate)}}><Typography sx={{fontSize:10}}>{won(stock.currentPrice)}</Typography><Typography sx={{fontSize:10}}>{won(dayChange(stock))} ({Number.isFinite(stock.priceChangeRate)?formatRate(stock.priceChangeRate):'—'})</Typography></Box></Card>
 <Stack spacing="6px">{type==='buy'?<>{date}{quantity}{price}</>:<><Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'8px'}}><DateField {...field} label="매수일자" value={lot?kst(lot.boughtAt):''} onChange={()=>{}} readOnly disabled/>{date}</Box><Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'8px'}}><NumberField {...field} label="매수수량" value={lot?.quantity??''} onChange={()=>{}} suffix="주" readOnly/>{quantity}</Box><Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'8px'}}><NumberField {...field} label="매수가격" value={lot?.unitPrice??''} onChange={()=>{}} suffix="원" readOnly/>{price}</Box></>}<FormTextField {...field} label="메모" value={form.memo} onChange={v=>update('memo',v)} inputRef={memoRef} onEnter={()=>void save()}/>{!editId&&<Box component="details" sx={{fontSize:10,color:colors.textMuted}}><Box component="summary">거래비용 입력</Box><NumberField {...field} label="거래비용" value={form.fee} onChange={v=>update('fee',v)} suffix="원" inputRef={feeRef} onEnter={()=>void save()}/></Box>}</Stack><Typography sx={{fontSize:14,fontWeight:700}}>거래 정보</Typography><Card sx={{p:'5px 14px',borderRadius:'8px',bgcolor:colors.surface,border:`1px solid ${colors.border}`}}><Summary label={type==='buy'?'매수금액':'매도금액'} value={won(Number.isFinite(amount)?amount:undefined)} color={type==='buy'?colors.marketFall:colors.marketRise}/>{type==='sell'&&<Summary label="예상 실현손익" value={won(profit)} color={getMarketColor(profit)}/>}<Summary label={editId?'현재 예수금':'거래 후 예수금'} value={won(afterCash)}/>{type==='buy'&&<Box data-testid="average-comparison" sx={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:1,alignItems:'center',height:18}}><Typography sx={{fontSize:10,color:colors.textMuted}}>매수 평균단가</Typography><Typography sx={{fontSize:10,textAlign:'right'}}>변경 전 {won(previous)}</Typography><Typography sx={{fontSize:10,textAlign:'right',color:Number.isFinite(after)?after>previous?colors.marketFall:after<previous?colors.marketRise:colors.textPrimary:colors.textMuted}}>변경 후 {won(after)}</Typography></Box>}</Card>{editId&&<Typography sx={{fontSize:10,color:colors.textMuted}}>거래 수정 시 예수금과 과거 스냅샷은 자동 변경되지 않습니다.</Typography>}{!valid&&type==='sell'&&maximum!==undefined&&<Typography sx={{fontSize:10,color:colors.textMuted}}>매도 가능 {maximum.toLocaleString('ko-KR')}주 · 매수일 이후 날짜를 선택하세요.</Typography>}{error&&<Alert role="alert" severity="error">{error}</Alert>}<Stack direction="row" spacing="8px" data-testid="trade-actions" sx={{pt:'4px'}}><Button disabled={busy} onClick={close} variant="outlined" sx={{width:104,height:36,minHeight:36,borderRadius:'8px'}}>취소</Button><Button disabled={!valid||busy||saved.current} onClick={()=>void save()} variant="contained" sx={{flex:1,height:36,minHeight:36,borderRadius:'8px'}}>{busy?'저장 중':editId?'변경':type==='buy'?'매수':'매도'}</Button></Stack></Stack>;
}
function Summary({label,value,color=colors.textPrimary}:{label:string;value:string;color?:string}){return <Stack direction="row" sx={{height:18,justifyContent:'space-between',alignItems:'center'}}><Typography sx={{fontSize:10,color:colors.textMuted}}>{label}</Typography><Typography sx={{fontSize:11,color,fontWeight:600}}>{value}</Typography></Stack>;}
