import assert from 'node:assert/strict';
import test from 'node:test';
import { buildApp } from '../app.js';
import { prisma } from '../lib/prisma.js';
import { Prisma } from '../generated/prisma/index.js';
test('whole-master year/search selection, actual total, missing last and error distinct from empty',async()=>{
 const original=prisma.security.findMany;let args:any;let fail=false;
 prisma.security.findMany=(async(input:any)=>{args=input;if(fail)throw new Error('database unavailable');return [ {id:2n,name:'미수집',symbol:'002',valuationMetrics:[],marketPrice:null}, {id:1n,name:'미등록 종목',symbol:'001',marketPrice:{currentPrice:new Prisma.Decimal(10000),previousClosePrice:new Prisma.Decimal(9000),priceUpdatedAt:new Date()},valuationMetrics:[{metricDate:new Date('2024-12-31'),bps:new Prisma.Decimal(10000),roe:new Prisma.Decimal(10)}]}];}) as unknown as typeof original;
 const app=buildApp();try{const response=await app.inject('/api/value-analysis?year=2024&query=종목');assert.equal(response.statusCode,200);const data=response.json().data;assert.equal(data.total,2);assert.equal(data.rows[0].w,'1.2');assert.equal(data.rows[1].w,null);assert.equal(data.rows[0].requiredReturn,'8.0');assert.equal(data.rows[0].fairPrices[1].price,'12000');assert.equal(data.rows[0].excessEarnings,null);assert.equal(data.rows[0].shareholderValue,null);assert.equal(data.rows[1].issuedShares,null);assert.equal(data.rows[1].eps,null);assert.equal(args.where.watchlistItems,undefined);assert.equal(args.where.accountId,undefined);assert.equal(args.where.OR[1].symbol.contains,'종목');assert.equal(args.include.valuationMetrics.where.metricDate.gte.toISOString(),'2024-01-01T00:00:00.000Z');assert.equal((await app.inject('/api/value-analysis?year=bad')).statusCode,400);fail=true;assert.equal((await app.inject('/api/value-analysis')).statusCode,500);fail=false;prisma.security.findMany=(async()=>[]) as unknown as typeof original;assert.equal((await app.inject('/api/value-analysis')).json().data.total,0);}finally{await app.close();prisma.security.findMany=original;}
});
test('detail GET uses one repeatable-read snapshot, year metrics and requested stored periods',async()=>{
 const original=prisma.$transaction;let isolation:any;
 prisma.$transaction=(async(fn:any,options:any)=>{isolation=options.isolationLevel;return fn({security:{findUnique:async()=>({id:1n,name:'종목',symbol:'001',isActive:true,marketPrice:{currentPrice:new Prisma.Decimal(10000),priceUpdatedAt:new Date()}})},financialStatement:{findMany:async()=>[]},dartFinancialFiling:{findMany:async()=>[]},valuationMetric:{findMany:async()=>[{metricDate:new Date('2026-10-05'),bps:new Prisma.Decimal(10000),roe:new Prisma.Decimal(10)}]}});}) as unknown as typeof original;
 const app=buildApp();try{const response=await app.inject('/api/value-analysis/1?year=2026&mode=quarter&startYear=2025&startQuarter=4&count=10');assert.equal(response.statusCode,200);const data=response.json().data;assert.equal(isolation,'RepeatableRead');assert.equal(data.rows.length,10);assert.equal(data.rows[0].key,'2025:Q4');assert.equal(data.rows.at(-1).key,'2028:Q1');assert.equal(data.w,'1.2');assert.equal(data.fairPrices[1].price,'12000');assert.equal(data.rows[0].currentRatio,null);assert.equal((await app.inject('/api/value-analysis/1?mode=invalid')).statusCode,400);assert.equal((await app.inject('/api/value-analysis/1?count=11')).statusCode,400);}finally{await app.close();prisma.$transaction=original;}
});
