import { Box } from '@mui/material';
import type { ReactNode, RefObject } from 'react';
import { pageGutter, pageMetrics } from '../styles/tokens';

export function PageLayout({ children, scrollRef, valueChart = false, coverTop = 16, stockAdd = false, stocks = false, trade = false, journal = false, analysis = false, cash = false, more = false, home = false, targetFlow = false, assetOverview = false, collectionMonitoring = false, moreMenu = false, settings = false }: { valueChart?: boolean; children: ReactNode; scrollRef: RefObject<HTMLElement | null>; coverTop?: number; stockAdd?: boolean; stocks?: boolean; trade?: boolean; journal?: boolean; analysis?: boolean; cash?: boolean; more?: boolean; home?: boolean; targetFlow?: boolean; assetOverview?: boolean; collectionMonitoring?: boolean; moreMenu?: boolean; settings?: boolean }) {
  return <Box component="main" ref={scrollRef} sx={{ flex: 1, minHeight: 0, width: '100%', maxWidth: trade ? 880 : journal ? 'none' : collectionMonitoring ? { xs: 'none', sm: 816 } : { xs: 'none', sm: 816 }, mx: 'auto', px: cash ? '8px' : analysis ? '8px' : journal ? '8px' : stockAdd ? '8px' : home || assetOverview ? '8px' : stocks || settings || assetOverview || moreMenu ? '8px' : trade ? '8px' : collectionMonitoring ? '8px' : { xs: `${pageGutter.xs}px`, sm: `${pageGutter.sm}px` }, pt: cash ? 0 : analysis ? 0 : stocks || settings || moreMenu || trade || collectionMonitoring ? 0 : journal ? 0 : home || assetOverview ? 0 : stocks ? '14px' : more ? { xs: '8px', sm: '8px' } : { xs: `${coverTop}px`, sm: '16px' }, pb: valueChart ? '80px' : cash ? 0 : analysis ? { xs: '80px', sm: 0 } : stockAdd ? '80px' : stocks ? { xs: '80px', sm: 0 } : settings ? 0 : moreMenu ? '8px' : home || assetOverview || targetFlow ? '80px' : trade || collectionMonitoring ? 0 : journal ? 0 : more ? { xs: `${pageMetrics.bottomClearance}px`, sm: '8px' } : `${pageMetrics.bottomClearance}px`, overflowY: valueChart ? 'auto' : cash ? 'hidden' : analysis ? { xs: 'auto', sm: 'hidden' } : stockAdd ? 'auto' : stocks ? { xs: 'auto', sm: 'hidden' } : settings ? { xs: 'auto', sm: 'hidden' } : moreMenu ? 'hidden' : targetFlow ? 'auto' : collectionMonitoring ? { xs: 'auto', sm: 'hidden' } : assetOverview ? 'auto' : journal ? { xs: 'auto', sm: 'hidden' } : more ? { xs: 'auto', sm: 'hidden' } : 'auto', '@media (min-width: 600px) and (max-height: 424px)': assetOverview ? { overflowY: 'auto' } : {}, overflowX: 'hidden', overscrollBehaviorX: 'contain', overscrollBehaviorY: 'contain', scrollbarWidth: 'none', '&::-webkit-scrollbar': { display: 'none' } }}>
    {children}
  </Box>;
}


