USE roxstock;
SELECT 'COUNT', 'accounts', COUNT(*) FROM `accounts`;
SELECT 'COUNT', 'account_watchlist_items', COUNT(*) FROM `account_watchlist_items`;
SELECT 'COUNT', 'buy_trades', COUNT(*) FROM `buy_trades`;
SELECT 'COUNT', 'cash_transactions', COUNT(*) FROM `cash_transactions`;
SELECT 'COUNT', 'collector_locks', COUNT(*) FROM `collector_locks`;
SELECT 'COUNT', 'collector_runs', COUNT(*) FROM `collector_runs`;
SELECT 'COUNT', 'collector_run_items', COUNT(*) FROM `collector_run_items`;
SELECT 'COUNT', 'compound_growth_goals', COUNT(*) FROM `compound_growth_goals`;
SELECT 'COUNT', 'compound_growth_plans', COUNT(*) FROM `compound_growth_plans`;
SELECT 'COUNT', 'daily_account_snapshots', COUNT(*) FROM `daily_account_snapshots`;
SELECT 'COUNT', 'daily_position_snapshots', COUNT(*) FROM `daily_position_snapshots`;
SELECT 'COUNT', 'dart_api_daily_usage', COUNT(*) FROM `dart_api_daily_usage`;
SELECT 'COUNT', 'dart_backfill_tasks', COUNT(*) FROM `dart_backfill_tasks`;
SELECT 'COUNT', 'dart_collector_state', COUNT(*) FROM `dart_collector_state`;
SELECT 'COUNT', 'dart_corp_mappings', COUNT(*) FROM `dart_corp_mappings`;
SELECT 'COUNT', 'dart_daily_company_checks', COUNT(*) FROM `dart_daily_company_checks`;
SELECT 'COUNT', 'dart_financial_filings', COUNT(*) FROM `dart_financial_filings`;
SELECT 'COUNT', 'dart_report_cache', COUNT(*) FROM `dart_report_cache`;
SELECT 'COUNT', 'dart_security_state', COUNT(*) FROM `dart_security_state`;
SELECT 'COUNT', 'dividends', COUNT(*) FROM `dividends`;
SELECT 'COUNT', 'financial_statements', COUNT(*) FROM `financial_statements`;
SELECT 'COUNT', 'market_prices', COUNT(*) FROM `market_prices`;
SELECT 'COUNT', 'realtime_collector_issues', COUNT(*) FROM `realtime_collector_issues`;
SELECT 'COUNT', 'realtime_cycle_aggregates', COUNT(*) FROM `realtime_cycle_aggregates`;
SELECT 'COUNT', 'realtime_worker_state', COUNT(*) FROM `realtime_worker_state`;
SELECT 'COUNT', 'securities', COUNT(*) FROM `securities`;
SELECT 'COUNT', 'security_fundamentals', COUNT(*) FROM `security_fundamentals`;
SELECT 'COUNT', 'sell_trades', COUNT(*) FROM `sell_trades`;
SELECT 'COUNT', 'trade_requests', COUNT(*) FROM `trade_requests`;
SELECT 'COUNT', 'valuation_metrics', COUNT(*) FROM `valuation_metrics`;
SELECT 'COUNT', 'watchlist_items', COUNT(*) FROM `watchlist_items`;
SELECT 'COUNT', '_prisma_migrations', COUNT(*) FROM `_prisma_migrations`;
CHECKSUM TABLE `accounts`,`account_watchlist_items`,`buy_trades`,`cash_transactions`,`collector_locks`,`collector_runs`,`collector_run_items`,`compound_growth_goals`,`compound_growth_plans`,`daily_account_snapshots`,`daily_position_snapshots`,`dart_api_daily_usage`,`dart_backfill_tasks`,`dart_collector_state`,`dart_corp_mappings`,`dart_daily_company_checks`,`dart_financial_filings`,`dart_report_cache`,`dart_security_state`,`dividends`,`financial_statements`,`market_prices`,`realtime_collector_issues`,`realtime_cycle_aggregates`,`realtime_worker_state`,`securities`,`security_fundamentals`,`sell_trades`,`trade_requests`,`valuation_metrics`,`watchlist_items`,`_prisma_migrations` EXTENDED;
SELECT 'BALANCE',id,cash_balance FROM accounts ORDER BY id; SELECT 'CASH_SUM',account_id,transaction_type,COUNT(*),SUM(amount),SUM(fee_tax_amount) FROM cash_transactions GROUP BY account_id,transaction_type ORDER BY account_id,transaction_type; SELECT 'DIVIDEND_LINK',c.id,c.account_id,c.transaction_date,c.amount,c.balance_after,c.memo,d.id,d.security_id,s.symbol,s.name,d.gross_amount,d.net_amount,d.memo FROM cash_transactions c LEFT JOIN dividends d ON d.cash_transaction_id=c.id LEFT JOIN securities s ON s.id=d.security_id WHERE c.id IN (81,85) ORDER BY c.id;
SELECT 'ORPHAN','account_watchlist_items','account_watchlist_items_account_id_fkey',COUNT(*) FROM `account_watchlist_items` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','account_watchlist_items','account_watchlist_items_security_id_fkey',COUNT(*) FROM `account_watchlist_items` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','buy_trades','buy_trades_account_id_fkey',COUNT(*) FROM `buy_trades` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','buy_trades','buy_trades_security_id_fkey',COUNT(*) FROM `buy_trades` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','cash_transactions','cash_transactions_account_id_fkey',COUNT(*) FROM `cash_transactions` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','cash_transactions','cash_transactions_buy_trade_id_fkey',COUNT(*) FROM `cash_transactions` c LEFT JOIN `buy_trades` p ON c.`buy_trade_id`=p.`id` WHERE c.`buy_trade_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','cash_transactions','cash_transactions_sell_trade_id_fkey',COUNT(*) FROM `cash_transactions` c LEFT JOIN `sell_trades` p ON c.`sell_trade_id`=p.`id` WHERE c.`sell_trade_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','collector_run_items','collector_run_items_run_id_fkey',COUNT(*) FROM `collector_run_items` c LEFT JOIN `collector_runs` p ON c.`run_id`=p.`id` WHERE c.`run_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','collector_run_items','collector_run_items_security_id_fkey',COUNT(*) FROM `collector_run_items` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','compound_growth_goals','compound_growth_goals_plan_id_fkey',COUNT(*) FROM `compound_growth_goals` c LEFT JOIN `compound_growth_plans` p ON c.`plan_id`=p.`id` WHERE c.`plan_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','compound_growth_plans','compound_growth_plans_account_id_fkey',COUNT(*) FROM `compound_growth_plans` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','daily_account_snapshots','daily_account_snapshots_account_id_fkey',COUNT(*) FROM `daily_account_snapshots` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','daily_position_snapshots','daily_position_snapshots_account_id_fkey',COUNT(*) FROM `daily_position_snapshots` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','daily_position_snapshots','daily_position_snapshots_security_id_fkey',COUNT(*) FROM `daily_position_snapshots` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dart_backfill_tasks','dart_backfill_tasks_security_id_fkey',COUNT(*) FROM `dart_backfill_tasks` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dart_corp_mappings','dart_corp_mappings_security_id_fkey',COUNT(*) FROM `dart_corp_mappings` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dart_daily_company_checks','dart_daily_company_checks_security_id_fkey',COUNT(*) FROM `dart_daily_company_checks` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dart_financial_filings','dart_financial_filings_security_id_fkey',COUNT(*) FROM `dart_financial_filings` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dart_security_state','dart_security_state_security_id_fkey',COUNT(*) FROM `dart_security_state` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dividends','dividends_account_id_fkey',COUNT(*) FROM `dividends` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dividends','dividends_cash_transaction_id_fkey',COUNT(*) FROM `dividends` c LEFT JOIN `cash_transactions` p ON c.`cash_transaction_id`=p.`id` WHERE c.`cash_transaction_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','dividends','dividends_security_id_fkey',COUNT(*) FROM `dividends` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','financial_statements','financial_statements_security_id_fkey',COUNT(*) FROM `financial_statements` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','market_prices','market_prices_security_id_fkey',COUNT(*) FROM `market_prices` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','security_fundamentals','security_fundamentals_security_id_fkey',COUNT(*) FROM `security_fundamentals` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','sell_trades','sell_trades_buy_trade_id_fkey',COUNT(*) FROM `sell_trades` c LEFT JOIN `buy_trades` p ON c.`buy_trade_id`=p.`id` WHERE c.`buy_trade_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','trade_requests','trade_requests_account_id_fkey',COUNT(*) FROM `trade_requests` c LEFT JOIN `accounts` p ON c.`account_id`=p.`id` WHERE c.`account_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','valuation_metrics','valuation_metrics_security_id_fkey',COUNT(*) FROM `valuation_metrics` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
SELECT 'ORPHAN','watchlist_items','watchlist_items_security_id_fkey',COUNT(*) FROM `watchlist_items` c LEFT JOIN `securities` p ON c.`security_id`=p.`id` WHERE c.`security_id` IS NOT NULL AND p.`id` IS NULL;
