import assert from 'node:assert/strict';
import test from 'node:test';
import {Prisma,type DartFinancialFiling} from '../generated/prisma/index.js';
import {calculatePeriod,preserveValues} from './period-valuation.js';
const d=(n:number)=>new Prisma.Decimal(n);
function filing(year:number,period='ANNUAL',extra:object={}):DartFinancialFiling{return {securityId:1n,fiscalYear:year,periodType:period,fsDivision:'CFS',receiptNo:'20260301000001',receiptDate:new Date('2026-03-01'),periodEndDate:new Date(`${year}-12-31`),netIncomeYtd:d(20),totalEquity:d(220),accountSources:{},...extra} as DartFinancialFiling;}
test('annual ROE uses same-division average opening/closing equity, with explicit total basis',()=>{const result=calculatePeriod(filing(2025),filing(2024,'ANNUAL',{totalEquity:d(180)}));assert.equal(result.values.roe,'10');assert.equal(result.values.eps,null);assert.equal(result.provenance.roeBasis,'TOTAL_SAME_DIVISION');assert.equal(result.values.per,null);});
test('quarter uses YTD annualization, rejects mixed division and missing historical prices',()=>{const current=filing(2025,'Q2',{netIncomeYtd:d(10)});assert.equal(calculatePeriod(current,filing(2024,'ANNUAL',{totalEquity:d(180)})).values.roe,'10');assert.equal(calculatePeriod(current,filing(2024,'ANNUAL',{fsDivision:'OFS'})).values.roe,null);assert.equal(calculatePeriod(current,undefined,{price:{value:'100',date:'2026-10-07',source:'current'}}).values.per,null);});
test('disclosed EPS, exact-receipt ordinary shares, historical close and preferred share safeguard',()=>{const current=filing(2025,'ANNUAL',{accountSources:{basicEps:{amount:'10'},parentEquity:{amount:'200'}}});const sources={shares:{outstanding:'10',preferred:false,receiptNo:current.receiptNo},price:{value:'100',date:'2025-12-30',source:'FSC'}};const result=calculatePeriod(current,undefined,sources);assert.equal(result.values.eps,'10');assert.equal(result.values.bps,'20');assert.equal(result.values.per,'10');assert.equal(result.values.pbr,'5');assert.equal(calculatePeriod(current,undefined,{...sources,shares:{...sources.shares,preferred:true}}).values.bps,null);assert.equal(calculatePeriod(current,undefined,{...sources,shares:{...sources.shares,receiptNo:'different'}}).values.bps,null);});
test('idempotent preservation includes zero and negative manually stored values',()=>{const values={eps:'10',bps:'20',per:'5',pbr:'2',roe:'10'};assert.deepEqual(preserveValues({eps:'0',roe:'-3'},values),{...values,eps:'0',roe:'-3'});assert.deepEqual(preserveValues(values,values),values);});
