import {pageMetrics} from '../../styles/tokens';
import {useDetailSwipe} from '../../hooks/useDetailSwipe';
import {useStockNeighbors} from '../../hooks/useStockNeighbors';
import {FavoriteBorderRounded,FavoriteRounded} from '@mui/icons-material';
import {Alert,Box,Button,Card,CardContent,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,Skeleton,Stack,Tab,Tabs,Typography,useMediaQuery} from '@mui/material';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {useLocation,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {PageHeader} from '../../components/navigation/Navigation';
import {useFavoriteStocks} from '../../hooks/useFavoriteStocks';
import {deleteTrade,getBuyLots,getTradeDetail,getTrades,deleteWatchlistItem,updateWatchlistItem} from '../../data/roxstockApi';
import {useBuyLots,useStocks} from '../../hooks/useMockData';
import {useReturnNavigation,useListNavigation,usePageMemory} from '../../hooks/navigation/usePageMemory';
import {useActiveAccount} from '../../hooks/useActiveAccount';
import type {StockItem} from '../../types/models';
import {formatRate,getMarketColor} from '../../utils/format';
import {colors} from '../../styles/tokens';
import {dayChange,lotValue,stockValuation,won} from './stockMath';
import {PriceDialog} from './StockDialogs';
import {StockListPage} from './StockListPage';
export const money=won;
export function DetailCard({title,children}:{title:string;children:ReactNode}){return <Card sx={{borderRadius:'8px',border:`1px solid ${colors.border}`,bgcolor:colors.surface}}><CardContent sx={{p:'14px 16px !important'}}><Typography sx={{fontSize:14,fontWeight:700,mb:1}}>{title}</Typography>{children}</CardContent></Card>;}
export function DetailRow({label,value,color=colors.textPrimary}:{label:string;value:string;color?:string}){return <Stack direction="row" sx={{minHeight:25,alignItems:'center',justifyContent:'space-between',gap:1}}><Typography sx={{fontSize:12,color:colors.textMuted}}>{label}</Typography><Typography sx={{fontSize:12,fontWeight:600,textAlign:'right',color}}>{value}</Typography></Stack>;}
export function useStockFormNavigation(){const navigate=useListNavigation(),location=useLocation();return (path:string)=>navigate(path,{state:{backgroundLocation:location}});}
export function LiveStockDetailPage(){
 const {stockId=''}=useParams(),[params]=useSearchParams(),location=useLocation(),navigate=useNavigate(),back=useReturnNavigation(),tablet=useMediaQuery('(min-width:600px)');
 const {data:stocks,isPending,isError,refetch}=useStocks();const {favoriteIds,toggleFavorite}=useFavoriteStocks();const stock=stocks?.find(s=>s.id===stockId);
 const {previous,next}=useStockNeighbors(stockId,stocks??[]);
 const move=(offset:number)=>{const target=offset<0?previous:next;if(target)navigate(`/stocks/${target.id}${location.search}`,{replace:true,state:location.state});};
 const swipe=useDetailSwipe(move,!!stock);
 if(tablet&&stock)return <StockListPage initialSelectedId={stockId} initialTab={stock.listType}/>;
 return <Stack spacing={1} {...swipe} data-detail-swipe sx={{touchAction:'pan-y',minHeight:`calc(100dvh - ${pageMetrics.headerHeight * 2}px)`}}><PageHeader embedded stockNavigation={stock&&(previous||next)?<Stack direction="row" sx={{justifyContent:'space-between',alignItems:'center'}}>
 <Button disabled={!previous} onClick={()=>move(-1)} sx={{fontSize:10,p:0,minWidth:0,minHeight:14,height:14,lineHeight:'14px',color:colors.textMuted}}>{previous?.name??''}</Button><Typography sx={{fontSize:10,color:colors.textMuted}}>{stock.symbol}</Typography>
 <Button disabled={!next} onClick={()=>move(1)} sx={{fontSize:10,p:0,minWidth:0,minHeight:14,height:14,lineHeight:'14px',color:colors.textMuted}}>{next?.name??''}</Button></Stack>:undefined}
 title={stock?.name??'종목 상세'} onBack={back} showAdd={false} action={stock&&<IconButton aria-label="즐겨찾기" onClick={()=>toggleFavorite(stock.id)} sx={{color:favoriteIds.has(stock.id)?colors.warning:colors.textMuted}}>{favoriteIds.has(stock.id)?<FavoriteRounded/>:<FavoriteBorderRounded/>}</IconButton>}/>
 {isPending?<Skeleton height={64}/>:isError&&!stocks?<Button role="alert" onClick={()=>void refetch()}>종목 조회 실패 · 다시 시도</Button>:stock?<StockDetailContent key={stock.id} stock={stock} initialTab={params.get('tab')==='trades'||stock.listType==='traded'?'trades':'holding'}/>:<Typography>내용이 없습니다.</Typography>}</Stack>;
}
export function StockDetailContent(props:{stock:StockItem;initialTab?:'holding'|'summary'|'trades'}) {const {accountId}=useActiveAccount();return <AccountStockDetail key={`${accountId}:${props.stock.id}`} {...props}/>;}
function AccountStockDetail({stock,initialTab='holding'}:{stock:StockItem;initialTab?:'holding'|'summary'|'trades'}) {
 const navigate=useNavigate(),openForm=useStockFormNavigation(),queryClient=useQueryClient(),tablet=useMediaQuery('(min-width:600px)');const {accountId}=useActiveAccount();
 const [detailParams]=useSearchParams();
 const requestedTab=detailParams.get('detailTab');
 const [tab,setTab]=usePageMemory('stockDetailTab:'+stock.id,requestedTab==='holding'||requestedTab==='trades'?requestedTab:initialTab),[priceOpen,setPriceOpen]=useState(false),[remove,setRemove]=useState<{id:string;type:'buy'|'sell';lotId:string}|null>(null),[categoryOpen,setCategoryOpen]=useState(false),[listDeleteOpen,setListDeleteOpen]=useState(false),[category,setCategory]=useState<'WATCHLIST'|'RECOMMENDED'|'HOLDING'>(stock.listType==='holding'?'HOLDING':stock.listType==='recommended'?'RECOMMENDED':'WATCHLIST'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false),alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const {data:lots,isPending:lotsPending,isError:lotsError,refetch:reloadLots}=useBuyLots(stock.id);
 const trades=useQuery({queryKey:['stockTrades',accountId,stock.id],staleTime:30_000,enabled:!!accountId,queryFn:()=>getTrades(accountId!,{securityId:stock.id})});
 const allLots=useQuery({queryKey:['allBuyLots',accountId,stock.id],staleTime:30_000,enabled:!!accountId&&tab==='trades',queryFn:()=>getBuyLots(accountId!,stock.id,false)});
 const deletion=useQuery({queryKey:['tradeDetail',accountId,remove?.type,remove?.id],enabled:!!accountId&&!!remove,queryFn:()=>getTradeDetail(remove!.type,remove!.id,accountId)});
 const holding=stock.listType==='holding',traded=stock.listType==='traded',valuation=stockValuation(stock);
 const canChangeCategory=!!stock.watchlistItemId&&stock.hasTradeHistory!==true&&!traded&&!!trades.data&&!trades.isError&&trades.data.data.length===0&&(!holding||tab==='summary'||tab==='holding'&&!lotsPending&&!lotsError&&!!lots?.some(l=>l.remainingQuantity>0));
 useEffect(()=>{if(!canChangeCategory)setCategoryOpen(false);},[canChangeCategory]);
 const [visibleYears,setVisibleYears]=usePageMemory('stockTradeYears:'+stock.id,1);
 useEffect(()=>{setError('');setRemove(null);setPriceOpen(false);setCategoryOpen(false);setListDeleteOpen(false);},[stock.id,accountId]);
 const refresh=()=>Promise.all(['stocks','buyLots','allBuyLots','stockTrades','dashboard','targetArrivals','recentBuys','journalTrades','tradeDetail','cashOverview','cashTransactions'].map(key=>queryClient.invalidateQueries({queryKey:[key]})));
 const removeTrade=async()=>{if(!remove||lock.current||!deletion.data||deletion.data.account.id!==accountId||remove.type==='buy'&&!!deletion.data.sellTrades?.length)return;lock.current=true;setBusy(true);setError('');try{await deleteTrade(remove.type,remove.id,false,accountId);await refresh();if(alive.current)setRemove(null);}catch(e){if(alive.current)setError(e instanceof Error?e.message:'삭제 실패');}finally{lock.current=false;if(alive.current)setBusy(false);}};
 const saveCategory=async()=>{if(!stock.watchlistItemId||lock.current||!canChangeCategory)return;lock.current=true;setBusy(true);try{await updateWatchlistItem(stock.watchlistItemId,{accountId,listType:category});await refresh();if(alive.current){setCategoryOpen(false);navigate(`/stocks?tab=${category==='HOLDING'?'holding':category==='WATCHLIST'?'watchlist':'recommended'}`);}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'분류 변경 실패');}finally{if(alive.current)setBusy(false);lock.current=false;}};
 const sellEntries=trades.data?.data.filter(t=>t.type==='SELL')??[];const years=[...new Set(sellEntries.map(t=>new Date(t.tradedAt).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}).slice(0,4)))].sort().reverse();
 const edit=(type:'buy'|'sell',id:string,lotId?:string)=>openForm(`/trade?${new URLSearchParams({type,stock:stock.id,edit:id,...(lotId?{lot:lotId}:{})})}`);
 return <Stack spacing="8px" data-testid="stock-detail-content" data-list-condition={JSON.stringify([stock.id,tab])} data-restoration-ready={tab==='holding'?(!lotsPending||lotsError):tab==='trades'?(!trades.isPending&&!allLots.isPending||trades.isError||allLots.isError):true} sx={{pb:'80px',minWidth:0}}>
  {error&&<Alert role="alert" severity="error">{error}</Alert>}
  <Card sx={{height:64,p:'8px 16px',borderRadius:'8px',border:`1px solid ${colors.border}`,bgcolor:colors.surface,display:'flex',alignItems:'center',justifyContent:'space-between'}}><Box><Typography sx={{fontSize:22,lineHeight:'28px',fontWeight:600,color:getMarketColor(stock.priceChangeRate)}}>{won(valuation.price)}</Typography><Button onClick={()=>tablet?setPriceOpen(true):navigate(`/stocks/${stock.id}/price`)} sx={{p:0,minWidth:0,minHeight:18,height:18,fontSize:12,lineHeight:'18px',color:getMarketColor(stock.priceChangeRate)}}>{won(dayChange(stock))} ({stock.priceAvailable!==false&&stock.priceChangeAvailable!==false&&Number.isFinite(stock.priceChangeRate)?formatRate(stock.priceChangeRate,2):'—'})</Button></Box><Button onClick={()=>openForm(`/trade?type=buy&stock=${stock.id}`)} sx={{height:32,minHeight:32,borderRadius:'8px',minWidth:58,bgcolor:colors.raised,fontSize:12}}>매수</Button></Card>
  {holding||traded?<><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="fullWidth" sx={{p:'4px',minHeight:40,bgcolor:colors.surface,borderRadius:'8px','& .MuiTabs-indicator':{display:'none'},'& .MuiTab-root':{minWidth:0,minHeight:32,p:0,fontSize:12,color:colors.textMuted,borderRadius:'8px'},'& .Mui-selected':{bgcolor:colors.buttonPrimary,color:'#fff !important'}}}><Tab value="summary" label="요약"/><Tab value="holding" label="보유 현황"/><Tab value="trades" label="거래내역"/></Tabs>
  {tab==='holding'&&(lotsPending?<Skeleton height={198}/>:lotsError?<Button role="alert" onClick={()=>void reloadLots()}>Lot 조회 실패 · 다시 시도</Button>:lots?.some(l=>l.remainingQuantity>0)?lots.filter(l=>l.remainingQuantity>0).map(lot=>{const value=lotValue(lot,stock.priceAvailable===false?Number.NaN:stock.currentPrice),color=getMarketColor(value.profit);return <Card key={lot.id} data-testid={`lot-${lot.id}`} data-scroll-item={lot.id} sx={{p:'12px 16px',borderRadius:'8px',border:`1px solid ${colors.border}`,bgcolor:colors.surface}}><Box role="button" tabIndex={0} aria-label={`${lot.tradeDate} Lot 매도`} onClick={()=>openForm(`/trade?type=sell&stock=${stock.id}&lot=${lot.id}`)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();openForm(`/trade?type=sell&stock=${stock.id}&lot=${lot.id}`);}}} sx={{cursor:'pointer'}}><Stack direction="row" sx={{justifyContent:'space-between',mb:1}}><Typography sx={{fontSize:12,color:colors.textMuted}}>{lot.tradeDate.replaceAll('-','.')}</Typography><Typography sx={{fontSize:12,color:colors.textMuted}}>보유 {Math.max(0,Math.floor((Date.now()-new Date(lot.tradeDate+'T00:00:00+09:00').getTime())/86400000))}일</Typography></Stack><LotRow label="매수" formula={`${lot.remainingQuantity.toLocaleString('ko-KR')} × ${won(lot.buyPrice)}`} amount={won(lot.remainingQuantity*lot.buyPrice)}/><LotRow label="평가" formula={`${lot.remainingQuantity.toLocaleString('ko-KR')} × ${won(valuation.price)}`} amount={won(value.amount)} color={color}/><LotRow label="수익률" formula={Number.isFinite(value.rate)?formatRate(value.rate):'—'} amount={won(value.profit)} color={color}/></Box><Box sx={{height:1,bgcolor:colors.border,mt:1,mb:1}}/><Stack direction="row" sx={{justifyContent:'space-between',alignItems:'center'}}><Typography sx={{fontSize:12,fontWeight:600}}>목표수익률</Typography><Stack direction="row" spacing={1}><IconButton aria-label={`${lot.id} 매수 수정`} onClick={e=>{e.stopPropagation();edit('buy',lot.id);}} sx={{width:24,height:24,p:0}}><Box component="img" src="/stocks-v03/edit.svg" alt=""/></IconButton><IconButton aria-label={`${lot.id} 매수 삭제`} onClick={e=>{e.stopPropagation();setRemove({id:lot.id,type:'buy',lotId:lot.id});}} sx={{width:24,height:24,p:0}}><Box component="img" src="/stocks-v03/delete.svg" alt=""/></IconButton></Stack></Stack><Stack direction="row" spacing={1} sx={{mt:0.5}}>{[5,10,15].map(rate=><Box key={rate} sx={{flex:1,minWidth:0,p:'4px 6px',border:`1px solid ${colors.marketRise}55`,borderRadius:'8px'}}><Stack direction="row" sx={{justifyContent:'space-between'}}><Typography sx={{fontSize:10,color:colors.marketRise}}>{rate}%</Typography><Typography sx={{fontSize:10}}>{won(lot.buyPrice*(1+rate/100))}</Typography></Stack><Typography sx={{fontSize:9,textAlign:'right',color:colors.textMuted}}>{won(lot.remainingQuantity*lot.buyPrice*(1+rate/100))}</Typography></Box>)}</Stack></Card>;}):<Empty/>)}
  {tab==='summary'&&<><DetailCard title="보유 요약"><DetailRow label="평균단가" value={`${stock.quantity??'—'}주　${won(stock.averagePrice)}`}/><DetailRow label="매입금액" value={won(stock.purchaseAmount)}/><DetailRow label="평가금액" value={won(valuation.amount)}/><DetailRow label="평가손익" value={won(valuation.profit)} color={getMarketColor(valuation.profit)}/></DetailCard><DetailCard title="거래 요약"><DetailRow label="매수" value={won(trades.data?Number(trades.data.summary.buyAmount):undefined)}/><DetailRow label="매도" value={won(trades.data?Number(trades.data.summary.sellAmount):undefined)}/><DetailRow label="실현손익" value={won(trades.data?Number(trades.data.summary.realizedProfitLoss):undefined)} color={getMarketColor(trades.data?Number(trades.data.summary.realizedProfitLoss):Number.NaN)}/></DetailCard></>}
  {tab==='trades'&&(trades.isPending||allLots.isPending?<Skeleton height={180}/>:trades.isError||allLots.isError?<Button role="alert" onClick={()=>{void trades.refetch();void allLots.refetch();}}>거래 조회 실패 · 다시 시도</Button>:years.length?<>{years.slice(0,visibleYears).map(year=>{const entries=sellEntries.filter(t=>new Date(t.tradedAt).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}).startsWith(year));return <Box component="section" key={year} data-testid={`trade-year-${year}`}><Stack data-testid="trade-year-title" direction="row" sx={{position:'sticky',top:0,zIndex:2,height:38,px:'16px',mb:'8px',bgcolor:colors.raised,alignItems:'center',justifyContent:'space-between'}}><Typography sx={{fontSize:14,fontWeight:700}}>{year}년</Typography><Typography sx={{fontSize:11,color:colors.textMuted}}>{entries.length}건</Typography><Typography sx={{fontSize:14,fontWeight:600,color:getMarketColor(entries.reduce((s,t)=>s+Number(t.realizedProfitLoss??0),0))}}>{won(entries.reduce((s,t)=>s+Number(t.realizedProfitLoss??0),0))}</Typography></Stack><Stack spacing={1}>{entries.map(entry=>{const lot=allLots.data?.find(l=>l.id===entry.buyTradeId),profit=Number(entry.realizedProfitLoss),color=getMarketColor(profit);return <Card key={entry.id} data-testid={`sell-${entry.id}`} data-scroll-item={entry.id} sx={{p:'8px 16px',borderRadius:'8px',bgcolor:colors.surface,border:`1px solid ${colors.border}`}}><Stack direction="row" sx={{alignItems:'center',justifyContent:'space-between',mb:0.5}}><Typography sx={{fontSize:16,fontWeight:600,color}}>{won(profit)}　{lot&&Number(lot.unitPrice)>0?formatRate((Number(entry.unitPrice)/Number(lot.unitPrice)-1)*100):'—'}</Typography><Stack direction="row"><IconButton aria-label={`${entry.id} 매도 수정`} onClick={e=>{e.stopPropagation();edit('sell',entry.id,entry.buyTradeId);}} sx={{p:0,width:24,height:24}}><Box component="img" src="/stocks-v03/edit.svg" alt=""/></IconButton><IconButton aria-label={`${entry.id} 매도 삭제`} onClick={e=>{e.stopPropagation();setRemove({id:entry.id,type:'sell',lotId:entry.buyTradeId});}} sx={{p:0,width:24,height:24}}><Box component="img" src="/stocks-v03/delete.svg" alt=""/></IconButton></Stack></Stack><LotRow label="매수" formula={`${Number(entry.quantity).toLocaleString('ko-KR')} × ${won(lot?Number(lot.unitPrice):undefined)}`} amount={won(lot?Number(entry.quantity)*Number(lot.unitPrice):undefined)}/><LotRow label="매도" formula={`${Number(entry.quantity).toLocaleString('ko-KR')} × ${won(Number(entry.unitPrice))}`} amount={won(Number(entry.amount))} color={colors.marketRise}/><Typography sx={{fontSize:10,color:colors.textMuted,textAlign:'right'}}>{new Date(entry.tradedAt).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'})}</Typography></Card>;})}</Stack></Box>;})}{visibleYears<years.length&&<Button onClick={()=>setVisibleYears(visibleYears+1)} sx={{fontSize:12}}>이전 연도 더보기</Button>}</>:<Empty/>)}
  </>:<><DetailCard title="종목 정보"><DetailRow label="주요지표" value={`PER ${stock.per??'—'} · PBR ${stock.pbr??'—'} · ROE ${stock.roe??'—'}%`}/>{stock.note&&<Typography sx={{fontSize:12,color:colors.textMuted}}>{stock.note}</Typography>}{canChangeCategory&&<Button onClick={()=>setCategoryOpen(true)}>{stock.listType==='recommended'?'추천종목':'관심종목'} · 분류 변경</Button>}<Button onClick={()=>setListDeleteOpen(true)}>목록 삭제</Button></DetailCard><Button variant="contained" onClick={()=>navigate(`/stocks/${stock.id}/value`)}>상세보기 ›</Button></>}
  {holding&&canChangeCategory&&<Button onClick={()=>setCategoryOpen(true)}>보유종목 · 분류 변경</Button>}
  <PriceDialog stock={priceOpen?stock:null} onClose={()=>setPriceOpen(false)}/>
  <Dialog open={!!remove} onClose={()=>!busy&&setRemove(null)} slotProps={{paper:{sx:{m:'16px',width:'calc(100% - 32px)',maxWidth:368,borderRadius:'8px',backgroundImage:'none'}}}}><DialogTitle>거래 삭제</DialogTitle><DialogContent>{deletion.isPending?'거래 확인 중':deletion.isError?<Button onClick={()=>void deletion.refetch()}>거래 조회 실패 · 다시 시도</Button>:<Typography sx={{fontSize:13}}>{stock.name} {remove?.type==='sell'?'매도':'매수'} {deletion.data?.quantity}주를 삭제할까요? {remove?.type==='sell'&&allLots.data?.find(l=>l.id===remove.lotId)&&`연결된 매수의 잔여수량은 ${allLots.data.find(l=>l.id===remove.lotId)!.remainingQuantity}주에서 ${Number(allLots.data.find(l=>l.id===remove.lotId)!.remainingQuantity)+Number(deletion.data?.quantity)}주로 복원됩니다.`}{remove?.type==='buy'&&deletion.data?.sellTrades?.length?`연결된 매도 ${deletion.data.sellTrades.length}건이 있어 매수 Lot을 삭제할 수 없습니다.`:''} 예수금은 자동 변경되지 않습니다.</Typography>}{error&&<Typography role="alert">{error}</Typography>}</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setRemove(null)}>취소</Button><Button disabled={busy||!deletion.data||deletion.data.account.id!==accountId||remove?.type==='buy'&&!!deletion.data.sellTrades?.length} onClick={()=>void removeTrade()}>삭제</Button></DialogActions></Dialog>
  <Dialog open={listDeleteOpen} onClose={()=>!busy&&setListDeleteOpen(false)} slotProps={{paper:{sx:{borderRadius:'8px'}}}}><DialogTitle>종목 삭제</DialogTitle><DialogContent><Typography>{stock.name}을 목록에서 삭제할까요?</Typography>{error&&<Typography role="alert">{error}</Typography>}</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setListDeleteOpen(false)}>취소</Button><Button disabled={busy} onClick={async()=>{if(!stock.watchlistItemId||lock.current)return;lock.current=true;setBusy(true);try{await deleteWatchlistItem(stock.watchlistItemId,accountId);await refresh();if(!alive.current)return;navigate('/stocks');setListDeleteOpen(false);}catch(e){if(alive.current)setError(e instanceof Error?e.message:'삭제 실패');}finally{lock.current=false;if(alive.current)setBusy(false);}}}>삭제</Button></DialogActions></Dialog>
  <Dialog open={categoryOpen&&canChangeCategory} onClose={()=>!busy&&setCategoryOpen(false)} slotProps={{paper:{sx:{borderRadius:'8px'}}}}><DialogTitle>종목 분류</DialogTitle><DialogContent><Stack spacing={1}><Button variant={category==='WATCHLIST'?'contained':'outlined'} onClick={()=>setCategory('WATCHLIST')}>관심종목</Button><Button variant={category==='HOLDING'?'contained':'outlined'} onClick={()=>setCategory('HOLDING')}>보유종목</Button></Stack>{error&&<Typography role="alert">{error}</Typography>}</DialogContent><DialogActions><Button onClick={()=>setCategoryOpen(false)}>취소</Button><Button disabled={busy} onClick={()=>void saveCategory()}>확인</Button></DialogActions></Dialog>
 </Stack>;
}
function Empty(){return <Typography sx={{py:4,fontSize:12,textAlign:'center',color:colors.textMuted}}>내용이 없습니다.</Typography>;}
function LotRow({label,formula,amount,color=colors.textPrimary}:{label:string;formula:string;amount:string;color?:string}){return <Box sx={{display:'grid',gridTemplateColumns:'40px minmax(0,1fr) auto',alignItems:'center',height:24,gap:'4px',color}}><Typography sx={{fontSize:11}}>{label}</Typography><Typography noWrap sx={{fontSize:12}}>{formula}</Typography><Typography sx={{fontSize:12,textAlign:'right',fontWeight:600}}>{amount}</Typography></Box>;}
