import {Box,Button,Dialog,IconButton,Stack,Typography} from '@mui/material';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useRef,useState} from 'react';
import type {StockItem} from '../../types/models';
import {getSecurityAnalysis,updateSecurityPrice} from '../../data/roxstockApi';
import {NumberField} from '../../components/forms/Fields';
import {formatRate,getMarketColor} from '../../utils/format';
import {colors} from '../../styles/tokens';
import {won} from './stockMath';
import {useNavigate} from 'react-router-dom';
export const stockDialogPaper={m:'16px',width:'calc(100% - 32px)',maxWidth:354,maxHeight:'calc(100dvh - 32px)',p:'16px',borderRadius:'8px',bgcolor:'#0B1322',border:'1px solid #2E4263',backgroundImage:'none'};
export function ValueIndicatorDialog({stock,onClose}:{stock:StockItem|null;onClose:()=>void}) {
 const navigate=useNavigate();const data=useQuery({queryKey:['securityAnalysis',stock?.id],enabled:!!stock,queryFn:()=>getSecurityAnalysis(stock!.id)});
 const analysis=data.data,latest=analysis?.statements.filter(s=>s.periodType==='ANNUAL').sort((a,b)=>b.fiscalYear-a.fiscalYear)[0];
 const amount=(v:string|null|undefined)=>v==null?'—':won(Number(v));
 const rows=[['주요지표',`PER ${analysis?.valuation?.per??stock?.per??'—'} · PBR ${analysis?.valuation?.pbr??stock?.pbr??'—'} · ROE ${analysis?.valuation?.roe??stock?.roe??'—'}%`],['지배순이익',amount(analysis?.fundamentals?.controllingProfit)],['발행주식수 (자기주식수)',`${analysis?.fundamentals?.issuedShares==null?'—':Number(analysis.fundamentals.issuedShares).toLocaleString('ko-KR')} (${analysis?.fundamentals?.treasuryShares==null?'—':Number(analysis.fundamentals.treasuryShares).toLocaleString('ko-KR')})`],['자산',amount(latest?.totalAssets)],['부채',amount(latest?.totalLiabilities)],['자본 (전년도)',`${amount(latest?.totalEquity)} (${amount(analysis?.fundamentals?.previousEquity)})`],['주당배당금',amount(analysis?.valuation?.dividendPerShare)],['배당수익률',analysis?.valuation?.dividendYield==null?'—':`${analysis.valuation.dividendYield}%`]];
 return <Dialog open={!!stock} onClose={onClose} slotProps={{paper:{sx:stockDialogPaper}}}><Stack spacing={1.5}><Stack direction="row" sx={{justifyContent:'space-between',alignItems:'center'}}><Typography sx={{fontSize:16,fontWeight:600}}>가치지표</Typography><IconButton aria-label="가치지표 닫기" onClick={onClose} sx={{p:0}}><Box component="img" src="/stocks-v03/close.svg" alt=""/></IconButton></Stack><Typography sx={{fontSize:13,fontWeight:600}}>{stock?.name}<Box component="span" sx={{fontSize:11,color:colors.textMuted}}> · A{stock?.symbol}</Box></Typography>{data.isError?<Button role="alert" onClick={()=>void data.refetch()}>가치지표 조회 실패 · 다시 시도</Button>:rows.map(([label,value])=><Stack key={label} direction="row" sx={{justifyContent:'space-between',gap:1}}><Typography sx={{fontSize:10,color:colors.textMuted}}>{label}</Typography><Typography sx={{fontSize:11,textAlign:'right'}}>{data.isPending?'—':value}</Typography></Stack>)}<Stack direction="row" sx={{justifyContent:'space-between',alignItems:'center'}}><Typography sx={{fontSize:10,color:colors.textMuted}}>{latest?`${latest.fiscalYear}년 연결 기준`:'재무 기준 미수집'}</Typography><Button size="small" sx={{fontSize:11,p:0}} onClick={()=>{onClose();navigate(`/stocks/${stock!.id}/value`);}}>상세보기 ›</Button></Stack></Stack></Dialog>;
}
export function PriceDialog({stock,onClose}:{stock:StockItem|null;onClose:()=>void}) {
 const queryClient=useQueryClient(),input=useRef<HTMLInputElement>(null),lock=useRef(false);const[value,setValue]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const current=value??(Number.isFinite(stock?.currentPrice)?String(stock?.currentPrice):'');const valid=current.trim()!==''&&Number.isFinite(Number(current))&&Number(current)>0;
 const save=async()=>{if(!stock||!valid||lock.current)return;lock.current=true;setBusy(true);setError('');try{await updateSecurityPrice(stock.id,current);await Promise.all(['stocks','securityAnalysis','targetArrivals','buyLots','dashboard'].map(key=>queryClient.invalidateQueries({queryKey:[key]})));setValue(null);onClose();}catch(cause){setError(cause instanceof Error?cause.message:'현재가 저장 실패');}finally{lock.current=false;setBusy(false);}};
 return <Dialog open={!!stock} onClose={()=>{if(!busy){setValue(null);onClose();}}} slotProps={{paper:{sx:{...stockDialogPaper,maxWidth:338}}}}><Stack spacing={1.5}><Typography sx={{fontSize:16,fontWeight:600}}>{stock?.name} · 현재가 수정</Typography><Typography sx={{fontSize:11,color:colors.textMuted}}>A{stock?.symbol}</Typography><Stack direction="row" sx={{justifyContent:'space-between'}}><Typography sx={{fontSize:11}}>자동 수집 현재가</Typography><Typography sx={{fontSize:13,color:getMarketColor(stock?.priceChangeRate??Number.NaN)}}>{won(stock?.currentPrice)}</Typography></Stack><NumberField label="변경할 현재가" value={current} onChange={setValue} suffix="원" size="small" clearIconSrc="/stocks-v03/clear.svg" autoFocus inputRef={input} onEnter={()=>void save()} disabled={busy}/>{error&&<Typography role="alert">{error}</Typography>}<Stack direction="row" spacing={1}><Button fullWidth variant="outlined" disabled={busy} onClick={()=>{setValue(null);onClose();}}>취소</Button><Button fullWidth variant="contained" disabled={!valid||busy} onClick={()=>void save()}>변경</Button></Stack><Typography sx={{fontSize:10,color:colors.textMuted}}>전일 대비 {stock&&Number.isFinite(stock.priceChangeRate)?formatRate(stock.priceChangeRate):'—'}</Typography></Stack></Dialog>;
}
