import { ArrowBackIosNewRounded } from '@mui/icons-material';
import { Box, Button, Card, CardContent, IconButton, Stack, Typography } from '@mui/material';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { stockItems } from '../../data/mockData';
import { colors } from '../../styles/tokens';

export function StockInsightPage({ mode }: { mode: 'value' | 'financials' }) {
  const navigate = useNavigate(); const { stockId = 'samsung' } = useParams();
  const stock = stockItems.find((item) => item.id === stockId) ?? stockItems.find((item) => item.id === 'samsung')!;
  const [annual, setAnnual] = useState(true);
  return <Stack spacing="12px" sx={{ pb: 2 }}>
    <Stack direction="row" sx={{ height: 40, alignItems: 'center', justifyContent: 'space-between' }}><IconButton onClick={() => navigate(-1)} sx={{ width: 36 }}><ArrowBackIosNewRounded sx={{ fontSize: 18 }} /></IconButton><Box sx={{ textAlign: 'center' }}><Typography sx={{ fontSize: 17, fontWeight: 600 }}>{stock.name}</Typography><Typography sx={{ fontSize: 10, color: colors.textMuted }}>{stock.symbol}</Typography></Box><Box sx={{ width: 36 }} /></Stack>
    {mode === 'value' ? <ValueContent stock={stock} /> : <FinancialContent annual={annual} onToggle={() => setAnnual((value) => !value)} />}
  </Stack>;
}

function ValueContent({ stock }: any) { return <><Card sx={{ borderRadius: '16px' }}><CardContent><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Typography sx={{ fontSize: 22, fontWeight: 600, color: colors.marketRise }}>{stock.currentPrice.toLocaleString()}원</Typography><Box sx={{ px: 1, py: 0.5, border: `1px solid ${colors.warning}`, borderRadius: '7px', color: colors.warning, fontSize: 10 }}>W {(stock.pbr ?? 1).toFixed(2)}</Box></Stack><Rows rows={[['전일대비','1,100원 (1.4%)'],['상승여력(W 0.8 기준)','28,000원 (35.0%)']]} /></CardContent></Card><Card sx={{ borderRadius: '16px' }}><CardContent><Typography sx={{ fontWeight: 700 }}>적정주가 <Box component="span" sx={{ float: 'right', fontSize: 10, color: colors.textMuted }}>RIM · 원</Box></Typography><Stack direction="row" spacing={0.75} sx={{ mt: 1.5 }}>{[['0.7','92,000'],['0.8','108,000'],['0.9','123,500'],['1.0','142,000']].map(([w,p]) => <Box key={w} sx={{ flex: 1, p: 1, border: `1px solid ${colors.disabled}`, borderRadius: '8px' }}><Typography sx={{ fontSize: 10 }}>W {w}</Typography><Typography sx={{ mt: 1, textAlign: 'right', color: colors.marketRise, fontSize: 11 }}>{p}원</Typography></Box>)}</Stack></CardContent></Card><Card sx={{ borderRadius: '16px' }}><CardContent><Typography sx={{ fontWeight: 700 }}>계산 기준 <Box component="span" sx={{ float: 'right', fontSize: 10, color: colors.textMuted }}>최근 결산</Box></Typography><Rows rows={[['자기자본','273조원'],['예상 ROE','13.4%'],['할인율','8.0%']]} /><Typography sx={{ mt: 1, fontSize: 10, color: colors.textMuted }}>※ 화면의 금액은 디자인 검토용 예시 데이터입니다.</Typography></CardContent></Card></>; }
function FinancialContent({ annual, onToggle }: { annual: boolean; onToggle: () => void }) { const metrics=[['매출액','조원','+7.5%',['258.9','281.4','302.5']],['영업이익','조원','+27.6%',['6.6','26.8','34.2']],['순이익','조원','+25.8%',['15.5','22.1','27.8']],['ROE','%','+2.1%p',['4.1','8.6','10.7']],['부채비율','%','-3.4%p',['26.4','24.8','21.4']]]; return <><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Typography sx={{ fontSize: 13, fontWeight: 600 }}>전체 재무지표</Typography><Button onClick={onToggle} variant="outlined" sx={{ minHeight: 34, height: 34, width: 80 }}>{annual ? '연간 ↕' : '분기 ↕'}</Button></Stack><Typography sx={{ color: colors.warning, fontSize: 13, fontWeight: 600 }}>수익성</Typography>{metrics.map((m,i)=><Card key={m[0] as string} sx={{ borderRadius: '16px' }}><CardContent sx={{ py: 1.25, '&:last-child':{pb:1.25} }}><Stack direction="row" sx={{ justifyContent: 'space-between' }}><Typography sx={{ fontSize: 14, fontWeight: 600 }}>{m[0]} <Box component="span" sx={{ fontSize: 9, color: colors.textMuted }}>{m[1]}</Box></Typography><Typography sx={{ fontSize: 11, color: i===4?colors.marketFall:colors.marketRise }}>{m[2]}</Typography></Stack><Stack direction="row" sx={{ mt: 1, justifyContent: 'space-around' }}>{(m[3] as string[]).map((v,j)=><Box key={v} sx={{ textAlign: 'center' }}><Typography sx={{ fontSize: 10, color: colors.textMuted }}>{annual ? 2024+j : `${j+1}Q`}</Typography><Typography sx={{ fontSize: 12, fontWeight:j===2?700:400 }}>{v}</Typography></Box>)}</Stack></CardContent></Card>)}</>; }
function Rows({ rows }: { rows: string[][] }) { return <Stack spacing={1} sx={{ mt: 1.5 }}>{rows.map(([l,v])=><Stack key={l} direction="row" sx={{ justifyContent: 'space-between' }}><Typography sx={{ fontSize: 12, color: colors.textMuted }}>{l}</Typography><Typography sx={{ fontSize: 12, fontWeight: 600 }}>{v}</Typography></Stack>)}</Stack>; }
