import {Box,Button,Typography} from '@mui/material';
import {useQuery} from '@tanstack/react-query';
import {useState} from 'react';
import {useLocation,useNavigate,useParams} from 'react-router-dom';
import {PageHeader} from '../../components/navigation/Navigation';
import {usePageMemory,useReturnNavigation} from '../../hooks/navigation/usePageMemory';
import {useDetailSwipe} from '../../hooks/useDetailSwipe';
import {FinancialRefreshControls} from '../stocks/FinancialRefreshControls';
import {format,number,seoulYear} from '../value/valueApi';
import {largeMoney} from '../../utils/largeMoney';
import {detailFinancials,listFinancials,type Field,type Row} from './financialApi';
const muted='#94A3B8',red='#F76B73',blue='#60A5FA',neutral='#F8FAFC',yellow='#FBBF24';
const control={font:'inherit',fontSize:12,color:neutral,background:'#111827',border:'1px solid #273244',borderRadius:8,height:28,padding:'0 24px 0 8px',appearance:'none' as const,backgroundImage:'url(/financial-v04/select-12.svg)',backgroundRepeat:'no-repeat',backgroundPosition:'right 4px center',minWidth:0,width:'100%'};
const groups:{title:string;fields:[Field,string][]}[]=[{title:'손익계산서',fields:[['revenue','매출액'],['operatingProfit','영업이익'],['netIncome','당기순이익'],['parentNetIncome','지배주주순이익']]},{title:'재무상태표',fields:[['totalAssets','자산'],['totalLiabilities','부채'],['totalEquity','자본'],['parentEquity','지배주주자본']]},{title:'현금흐름표',fields:[['operatingCashFlow','영업활동'],['investingCashFlow','투자활동'],['financingCashFlow','재무활동'],['cashEquivalents','기말현금']]}];
function tier(value:number|null){return value===null?muted:value>=30?red:value>=10?yellow:value>=0?neutral:blue;}
function rowColor(row:Row,key:keyof Row){if(key==='name')return neutral;const v=number(row[key]),price=number(row.currentPrice);if(v===null)return muted;
 if(key==='w')return v>1?red:blue;if(key==='roe')return v>10?red:blue;
 if(key==='capital')return v>=(row.market==='KOSPI'?1e12:1e11)?red:blue;
 if(key==='currentPrice'){const p=number(row.previousClosePrice);return p===null||p===v?neutral:v>p?red:blue;}
 if(key==='targetPrice')return price===null||v===price?neutral:v>price?red:blue;
 if(key==='eps'||key==='epsYield')return row.market==='KOSPI'?(v>=20?red:v>=10?yellow:v>=0?neutral:blue):neutral;
 if(key==='netIncome'){const equity=number(row.capital);return tier(equity!==null&&equity>0?v/equity*100:null);}return neutral;}
export function FinancialPage(){
 const location=useLocation(),navigate=useNavigate(),{stockId}=useParams(),backToSource=useReturnNavigation('/more'),currentYear=seoulYear();
 const params=new URLSearchParams(location.search),selected=stockId??params.get('selected'),detailView=!!selected&&params.get('view')!=='list';
 const [year,setYear]=usePageMemory('financial-year',currentYear),[market,setMarket]=usePageMemory('financial-market','KOSPI'),[query,setQuery]=usePageMemory('financial-query',''),[draft,setDraft]=usePageMemory('financial-draft',''),[sort,setSort]=usePageMemory('financial-sort',''),[direction,setDirection]=usePageMemory('financial-direction','desc');
 const [startYear,setStartYear]=usePageMemory('financial-start',currentYear-2),[mode,setMode]=usePageMemory<'annual'|'quarter'>('financial-mode','annual'),[quarter,setQuarter]=usePageMemory('financial-quarter',1),[chart,setChart]=useState(false),[showUpdate,setShowUpdate]=useState(false),[limit,setLimit]=useState(100);
 const list=useQuery({queryKey:['financialList',year,market,query,sort,direction],queryFn:({signal})=>listFinancials(year,market,query,sort,direction,signal),staleTime:30000});
 const detail=useQuery({queryKey:['financialDetail',selected,startYear,mode,quarter],queryFn:({signal})=>detailFinancials(selected!,startYear,mode,quarter,signal),enabled:detailView,staleTime:30000});
 const rows=list.data?.rows??[],index=rows.findIndex(r=>r.id===selected),previous=rows[index-1],next=rows[index+1];
 const choose=(id:string,replace=false)=>navigate('/detail/financials?'+new URLSearchParams({view:'detail',selected:id}),{replace,state:{...location.state,listEntryKey:location.state?.listEntryKey??location.key}});
 const move=(d:number)=>{const r=d<0?previous:next;if(r)choose(r.id,true);};
 const swipe=useDetailSwipe(move,detailView&&!showUpdate);
 const back=()=>{if(detailView&&!stockId){if(Number(window.history.state?.idx)>0)navigate(-1);else navigate('/detail/financials?view=list',{replace:true});}else backToSource();};
 const years=Array.from({length:currentYear-2015+1},(_,i)=>currentYear-i);
 const headers:(keyof Row)[][]=[['name','w'],['currentPrice','targetPrice','value','eps','epsYield'],['priceUpdatedAt','issuedShares','roe','capital','netIncome']];
 const names:Partial<Record<keyof Row,string>>={name:'종목명',w:'가중치(W)',currentPrice:'현재가',targetPrice:'목표가',value:'가치',eps:'주당순익',epsYield:'주당순익률',priceUpdatedAt:'시세일자',issuedShares:'주식수',roe:'ROE',capital:'자본',netIncome:'당기순이익'};
 const display=(r:Row,k:keyof Row)=>k==='name'?r.name:k==='issuedShares'?largeMoney(r[k]).replace(/원$/,''):k==='capital'||k==='netIncome'?largeMoney(r[k]):k==='priceUpdatedAt'?(r.priceUpdatedAt?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit'}).format(new Date(r.priceUpdatedAt)).replace(/\s/g,''):'?'):format(r[k],['w','value'].includes(k)?2:['epsYield','roe'].includes(k)?1:0,['epsYield','roe'].includes(k)?'%':['currentPrice','targetPrice','eps'].includes(k)?'원':'');
 const amountColor=(field:Field,growth:string|null)=>{const n=number(growth);return n===null||n===0||field==='financingCashFlow'?neutral:(field==='totalLiabilities'?n<0:n>0)?red:blue;};
 return <Box {...swipe} className="rox-home" data-testid="financial-page" data-restoration-ready={list.isPending?'false':'true'} sx={{fontFamily:'RoxHomeInter, sans-serif',fontSize:12,minHeight:'100%','& .MuiButton-root':{minHeight:0}}}>
 <PageHeader embedded valueAnalysis={detailView} variant="detail" title={detailView?detail.data?.security.name??rows[index]?.name??'재무제표':'재무제표'} showBackTablet showAdd={false} onBack={back}/>
 {!detailView?<><Box sx={{display:'flex',justifyContent:'space-between',gap:'16px',height:28,mb:'8px'}}>{[market==='KOSPI'?'KOSDAQ':'KOSPI',market,market==='KOSPI'?'KOSDAQ':'KOSPI'].map((m,i)=><Button key={i} aria-label={i===1?'현재 시장 '+m:(i===0?'이전':'다음')+' 시장 '+m} onClick={()=>{setMarket(m);setLimit(100);}} sx={{p:0,minWidth:0,fontSize:i===1?12:10,color:i===1?neutral:muted,fontWeight:400}}>{m}</Button>)}</Box>
 <Box component="form" onSubmit={e=>{e.preventDefault();setQuery(draft.trim());setLimit(100);}} sx={{display:'flex',gap:'8px',mb:'8px'}}><Box sx={{flex:1,minWidth:0,display:'flex',border:'1px solid #334052',borderRadius:'8px',bgcolor:'#0f1724'}}><input aria-label="재무제표 종목 검색" placeholder="종목명 또는 코드 검색" value={draft} onChange={e=>setDraft(e.target.value)} style={{...control,height:34,flex:1,border:0,background:'transparent',backgroundImage:'none'}}/><Button type="submit" aria-label="재무제표 검색" sx={{minWidth:38,p:0,fontSize:10,color:muted}}>검색</Button></Box><select aria-label="재무제표 기준연도" value={year} onChange={e=>setYear(Number(e.target.value))} style={{...control,height:36,width:104,backgroundImage:'url(/financial-v04/select-16.svg)'}}>{years.map(y=><option key={y} value={y}>{y}년</option>)}</select></Box>
 <Box sx={{display:'flex',justifyContent:'space-between',fontSize:10,color:muted,my:'8px'}}><span>총 {list.data?.total??0}개</span><span>{year}년 · 저장 데이터</span></Box><Box sx={{display:'grid',gap:'2px',pt:'4px',pb:'8px',borderBottom:'2px solid #738099',mb:'8px'}}>{headers.map((keys,i)=><Box key={i} sx={{display:'grid',gridTemplateColumns:i===0?'minmax(0,1fr) 84px':'70fr 70fr 42fr 82fr 90fr',gap:0}}>{keys.map(k=><button key={k} onClick={()=>{if(sort!==k){setSort(k);setDirection('asc');}else if(direction==='asc')setDirection('desc');else setSort('');}} style={{border:0,padding:0,background:'transparent',color:muted,fontSize:10,textDecoration:'underline',textAlign:['name','currentPrice','priceUpdatedAt'].includes(k)?'left':'right'}}>{sort===k?(direction==='desc'?'↓ ':'↑ '):''}{names[k]}</button>)}</Box>)}</Box>

 {rows.slice(0,limit).map(r=><Box component="button" key={r.id} onClick={()=>choose(r.id)} sx={{display:'grid',gap:'2px',width:'100%',border:0,borderBottom:'1px solid #334052',borderRadius:0,bgcolor:'transparent',p:'0 0 4px',mb:'8px',minHeight:58,fontFamily:'inherit',cursor:'pointer'}}>{headers.map((keys,i)=><Box key={i} sx={{display:'grid',gridTemplateColumns:i===0?'minmax(0,1fr) 84px':'70fr 70fr 42fr 82fr 90fr',gap:0}}>{keys.map(k=><Box key={k} sx={{fontSize:k==='name'?11:10,lineHeight:'16px',fontWeight:k==='name'?600:400,textAlign:['name','currentPrice','priceUpdatedAt'].includes(k)?'left':'right',color:rowColor(r,k),overflowWrap:'anywhere'}}>{display(r,k)}{k==='name'&&<span style={{fontSize:10,fontWeight:400,color:muted,marginLeft:4}}>{r.symbol}</span>}</Box>)}</Box>)}</Box>)}{rows.length>limit&&<Button onClick={()=>setLimit(n=>n+100)}>더 보기</Button>}{!list.isPending&&!rows.length&&!list.isError&&<Typography sx={{color:muted,textAlign:'center',py:'40px'}}>저장된 데이터가 없습니다.</Typography>}
 </>:<><Box sx={{display:'grid',gridTemplateColumns:'1fr auto 1fr',gap:'8px',mb:'8px',fontSize:10,color:muted,height:28,alignItems:'center'}}><Button disabled={!previous} onClick={()=>move(-1)} sx={{p:0,height:20,minHeight:20,minWidth:0,fontSize:10,justifyContent:'flex-start'}}>{previous?.name}</Button><span>{detail.data?.security.symbol??'?'}</span><Button disabled={!next} onClick={()=>move(1)} sx={{p:0,minWidth:0,fontSize:10,justifyContent:'flex-end'}}>{next?.name}</Button></Box>
 <Box sx={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:'8px',mb:'8px'}}><select aria-label="재무제표 시작연도" value={startYear} onChange={e=>setStartYear(Number(e.target.value))} style={control}>{years.map(y=><option key={y} value={y}>{y}년</option>)}</select><Button onClick={()=>setMode('annual')} sx={{...control,backgroundImage:'none',borderRadius:'8px',minHeight:28,p:0,color:neutral,bgcolor:mode==='annual'?'#3378e5':'#101827'}}>연간</Button><select aria-label="재무제표 시작분기" disabled={mode==='annual'} value={quarter} onChange={e=>setQuarter(Number(e.target.value))} style={{...control,opacity:mode==='annual'?.4:1}}>{[1,2,3,4].map(q=><option key={q} value={q}>{q}분기</option>)}</select><Button onClick={()=>setMode('quarter')} sx={{...control,backgroundImage:'none',p:0,color:neutral,bgcolor:mode==='quarter'?'#3378e5':'#101827',borderRadius:'8px'}}>분기</Button></Box>
 {detail.data&&<>{groups.map(group=><Box key={group.title} sx={{mb:'8px',p:'8px',bgcolor:'#101827',borderRadius:'8px'}}><Box sx={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'8px',mb:'8px'}}><Typography sx={{fontSize:14,fontWeight:700}}>{group.title}</Typography><span style={{fontSize:10,color:muted,textAlign:'right'}}>저장 데이터 · {Array.from(new Set(detail.data!.rows.flatMap(r=>r.basis?[r.basis.replace('DART:','').replace('MANUAL:','수동 ')]:[]))).join('/')} · 백만원</span></Box><Box component="table" sx={{width:'100%',borderCollapse:'collapse',tableLayout:'fixed',fontSize:10,'& th,& td':{p:'2px 0',height:24,textAlign:'right',fontWeight:400},'& th:first-of-type,& td:first-of-type':{textAlign:'left',width:90},'& thead':{color:muted,borderBottom:'1px solid #334155'},'& tbody tr:nth-of-type(even)':{color:muted}}}><thead><tr><th scope="col">항목</th>{detail.data.rows.map(r=><th key={r.key} scope="col">{r.label}{r.isDerived?'*':''}</th>)}</tr></thead><tbody>{group.fields.map(([field,label])=><FinancialTableRows key={field} label={label} rows={detail.data!.rows.map(r=>({key:r.key,value:r.values[field],growth:r.growth[field],color:amountColor(field,r.growth[field])}))}/>)}</tbody></Box></Box>)}
 <Box sx={{display:'flex',gap:'8px',mb:'8px'}}><Button onClick={()=>setChart(!chart)} sx={{fontSize:12}}>저장 데이터 차트 {chart?'닫기':'보기'}</Button><Button onClick={()=>setShowUpdate(!showUpdate)} sx={{fontSize:12}}>수동 업데이트</Button></Box>
 {chart&&<Box aria-label="매출액 차트" sx={{bgcolor:'#111827',borderRadius:'8px',p:'16px',mb:'8px'}}><Typography sx={{fontSize:12,mb:'8px'}}>매출액 · 백만원</Typography>{detail.data.rows.map(r=>{const value=number(r.values.revenue),max=Math.max(1,...detail.data!.rows.map(x=>Math.abs(number(x.values.revenue)??0)));return <Box key={r.key} sx={{display:'grid',gridTemplateColumns:'64px 1fr 64px',gap:'8px',alignItems:'center',fontSize:10,mb:'8px'}}><span>{r.label}</span><Box sx={{height:12,bgcolor:'#273244',borderRadius:'4px'}}>{value!==null&&<Box sx={{height:'100%',width:Math.abs(value)/max*100+'%',bgcolor:value<0?blue:red,borderRadius:'4px'}}/>}</Box><span style={{textAlign:'right'}}>{value===null?'?':format(value/1e6)}</span></Box>;})}</Box>}
 {showUpdate&&selected&&<FinancialRefreshControls key={selected} stockId={selected} collectedAt={detail.data.collectedAt} onSelection={()=>{}} fixedYear={startYear} allReports/>}
 <Typography sx={{fontSize:10,color:muted,lineHeight:'18px'}}>마지막 성공 수집: {detail.data.collectedAt?new Date(detail.data.collectedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'미수집'}<br/>{detail.data.notices.join(' ')} · * Q4는 연간 누계 − 3분기 누계입니다.</Typography></>}
 </>}
 {(detailView?detail.isError:list.isError)&&<Box role="alert">조회에 실패했습니다. 기존 저장 데이터는 유지됩니다.<Button onClick={()=>void(detailView?detail.refetch():list.refetch())}>다시 조회</Button></Box>}
 </Box>;
}
function FinancialTableRows({label,rows}:{label:string;rows:{key:string;value:string|null;growth:string|null;color:string}[]}){return <><tr><th scope="row">{label}</th>{rows.map(r=><td key={r.key} style={{color:r.color}}>{r.value===null?'—':format(Number(r.value)/1e6)}</td>)}</tr><tr><th scope="row" style={{fontWeight:400}}>전년 대비</th>{rows.map(r=><td key={r.key} style={{color:r.color}}>{format(r.growth,1,'%')}</td>)}</tr></>;}
