import {expect,test,type Page} from '@playwright/test';
async function setup(page:Page){await page.route('**/api/**',async route=>{const u=new URL(route.request().url());if(u.pathname.endsWith('/financial-refresh/active'))return route.fulfill({json:{data:null}});if(u.pathname==='/api/accounts')return route.fulfill({json:{data:[{id:'1',name:'계좌',isActive:true,isDefault:true}]}});const stocks=[1,2,3].map(i=>({id:String(i),name:'종목'+i,symbol:'00000'+i,currentPrice:'100',w:'1',fairPrices:[],valuation:null}));if(u.pathname==='/api/value-analysis')return route.fulfill({json:{data:{year:2026,rows:stocks,total:3}}});if(u.pathname.startsWith('/api/value-analysis/')){const id=u.pathname.split('/').at(-1),year=Number(u.searchParams.get('startYear')),mode=u.searchParams.get('mode'),q=Number(u.searchParams.get('startQuarter')),count=Number(u.searchParams.get('count'));if(id==='2')await new Promise(r=>setTimeout(r,100));return route.fulfill({json:{data:{security:stocks.find(s=>s.id===id),year:2026,mode,startYear:year,count,valuation:null,fairPrices:[],notices:[],rows:Array.from({length:count},(_,i)=>({key:String(i),label:String(year+i),year:year+i,quarter:mode==='annual'?null:q,revenue:'1000',netIncome:'10',roe:null,per:null,pbr:null,source:null,metricReasons:{roe:'동일 기준 자본 부족'}}))}}});}return route.fulfill({json:{data:[]}});});}
async function swipe(page:Page,dx:number){const n=page.getByText('재무지표',{exact:true});await n.dispatchEvent('touchstart',{touches:[{identifier:1,clientX:180,clientY:130}]});await n.dispatchEvent('touchmove',{touches:[{identifier:1,clientX:180+dx,clientY:134}]});await n.dispatchEvent('touchend',{touches:[],changedTouches:[{identifier:1,clientX:180+dx,clientY:134}]});}
test('chart conditions, boundaries, both swipes, chart protection, empty data and reload',async({page})=>{
 await setup(page);await page.goto('/detail/value?view=chart&selected=1&mode=annual&annualStart=2025&count=3');await expect(page.getByRole('heading',{name:/^종목1 /})).toBeVisible();await expect(page.getByRole('button',{name:'재무지표 중앙연도',exact:true})).toHaveText('2025');await page.getByRole('button',{name:'재무지표 중앙연도',exact:true}).click();await expect(page.getByRole('option').last()).toHaveText('2016');await page.keyboard.press('Escape');
 for(const [dx,id] of [[-100,2],[-100,3],[-100,3],[100,2],[100,1],[100,1]]){await swipe(page,dx);await expect(page).toHaveURL(new RegExp('selected='+id));await expect(page.getByRole('button',{name:'재무지표 중앙연도',exact:true})).toHaveText('2025');}
 const chart=page.getByTestId('value-chart-수익성');await chart.dispatchEvent('touchstart',{touches:[{identifier:1,clientX:180,clientY:180}]});await chart.dispatchEvent('touchend',{touches:[],changedTouches:[{identifier:1,clientX:50,clientY:180}]});await expect(page).toHaveURL(/selected=1/);
 await page.getByRole('button',{name:'분기',exact:true}).click();await page.getByLabel('시작기간').selectOption('2015:1');await swipe(page,-100);await expect(page.getByLabel('시작기간')).toHaveValue('2015:1');await expect(page).toHaveURL(/mode=quarter/);await expect(page).toHaveURL(/count=3/);await page.reload();await expect(page.getByLabel('시작기간')).toHaveValue('2015:1');await expect(page.getByRole('heading',{name:/^종목2 /})).toBeVisible();
});
test('rapid stock navigation ignores late responses and browser back restores entry conditions',async({page})=>{
 await setup(page);await page.goto('/detail/value?view=detail&selected=1&annualStart=2025&mode=annual&count=3');await expect(page.getByTestId('value-detail')).toBeVisible();
 await page.getByRole('button',{name:'재무지표 보기'}).click();await swipe(page,-100);await swipe(page,100);await page.waitForTimeout(180);await expect(page.getByRole('heading',{name:/^종목1 /})).toBeVisible();await expect(page.getByRole('button',{name:'재무지표 중앙연도',exact:true})).toHaveText('2025');
 await page.goBack();await expect(page.getByTestId('value-detail')).toBeVisible();await expect(page).toHaveURL(/selected=1/);await page.getByRole('button',{name:'재무지표 보기'}).click();await page.goBack();await expect(page.getByTestId('value-detail')).toBeVisible();await expect(page).toHaveURL(/centerYear=2025/);
});
test('financial table keeps year, quarter and chart visibility across neighbors and returns to list',async({page})=>{
 await setup(page);await page.route('**/api/financial-statements**',async route=>{const u=new URL(route.request().url());if(u.pathname.endsWith('/financial-refresh/active'))return route.fulfill({json:{data:null}});const rows=[{id:'1',symbol:'000001',name:'종목1',market:'KOSPI'},{id:'2',symbol:'000002',name:'종목2',market:'KOSPI'}];if(u.pathname.endsWith('/financial-statements'))return route.fulfill({json:{data:{rows,total:2}}});const id=u.pathname.split('/').at(-1);return route.fulfill({json:{data:{security:rows.find(r=>r.id===id),collectedAt:null,notices:[],rows:[{key:'2025:Q3',label:'2025 3Q',values:{},growth:{},basis:'CFS'}]}}});});
 await page.goto('/detail/financials');await page.getByRole('button',{name:/종목1.*000001/}).click();await page.getByRole('button',{name:'분기',exact:true}).click();await page.getByLabel('재무제표 시작연도').selectOption('2025');await page.getByLabel('재무제표 시작분기').selectOption('3');await page.getByRole('button',{name:'저장 데이터 차트 보기'}).click();await page.getByRole('button',{name:'종목2',exact:true}).click();await expect(page.getByLabel('재무제표 시작연도')).toHaveValue('2025');await expect(page.getByLabel('재무제표 시작분기')).toHaveValue('3');await expect(page.getByRole('button',{name:'저장 데이터 차트 닫기'})).toBeVisible();await expect(page).toHaveURL(/mode=quarter/);await expect(page).toHaveURL(/chart=true/);await page.goBack();await expect(page.getByLabel('재무제표 종목 검색')).toBeVisible();
});
