import {test,expect} from '@playwright/test';
import {fixture} from './stock-input-fixture';
test('negative cash buy requires explicit confirmation once',async({page})=>{
 const f=await fixture(page);await page.goto('/trade?type=buy&stock=1');await page.getByRole('textbox',{name:'매수수량',exact:true}).fill('1000');await page.getByRole('button',{name:'매수',exact:true}).click();await expect(page.getByRole('dialog').last()).toContainText('그래도 매수 하시겠습니까?');expect(f.writes).toHaveLength(0);await page.getByRole('button',{name:'확인',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);expect(f.writes[0].body.allowNegativeCash).toBe(true);
});
test('cash focus, required dividend selection and field order',async({page})=>{
 await fixture(page);await page.route('**/api/accounts/*/cash-overview*',r=>r.fulfill({json:{data:{account:{id:'a',currentBalance:'1000'},monthly:{},yearly:{},recentTransactions:[]}}}));await page.route('**/api/accounts/*/cash-transactions*',r=>r.fulfill({json:{data:[],meta:{total:0}}}));await page.goto('/detail/cash');await page.getByRole('button',{name:'예수금 등록',exact:true}).click();await expect(page.getByRole('textbox',{name:'금액',exact:true})).toBeFocused();await page.getByRole('button',{name:'배당',exact:true}).click();await expect(page.getByRole('textbox',{name:'세전 배당',exact:true})).toBeFocused();await expect(page.getByRole('combobox',{name:'배당 종목 선택'})).toContainText('종목을 선택하세요.');await page.getByRole('combobox',{name:'배당 종목 선택'}).click();await expect(page.getByRole('option',{name:'현대자동차'})).toHaveCount(1);await page.getByRole('option',{name:'현대자동차'}).click();const names=await page.getByTestId('cash-form').locator('input').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')).filter(Boolean));expect(names.indexOf('세전 배당')).toBeLessThan(names.indexOf('세후 배당'));expect(names.indexOf('세후 배당')).toBeLessThan(names.indexOf('세금'));
});
test('journal profit history and buy/sell details',async({page})=>{
 await fixture(page);await page.route('**/api/accounts/*/daily-position-profit*',r=>r.fulfill({json:{data:[{id:'1',name:'현대자동차',profit:'1000'}],meta:{available:true}}}));await page.goto('/journal?date=2026-09-18');await page.getByText('일별손익 보기',{exact:false}).click();await expect(page).toHaveURL(/view=profit/);await expect(page.getByTestId('daily-position-profit')).toContainText('현대자동차');await page.getByRole('button',{name:'매도 현대자동차 거래 상세'}).first().click();await expect(page).toHaveURL(/journal.*trade.*sell/);await expect(page.getByRole('heading',{name:'매도 거래 상세'})).toBeVisible();await page.goBack();await expect(page).toHaveURL(/view=profit/);await page.goBack();await expect(page).not.toHaveURL(/view=profit/);await expect(page.getByTestId('journal-day-card')).toBeVisible();await page.goto('/journal/trade/buy/lot1');await expect(page.getByRole('heading',{name:'매수 거래 상세'})).toBeVisible();await expect(page.getByText('원본 매수')).toBeVisible();
});
test('only latest cash buy editable independently of original trade',async({page})=>{
 const f=await fixture(page);const rows=[{id:'2',transactionType:'BUY',createdAt:'2026-10-06T02:00:00Z',transactionDate:'2026-10-06T02:00:00Z',amount:'100',signedAmount:'-100',feeTaxAmount:'0',memo:null,dividend:null},{id:'1',transactionType:'DEPOSIT',createdAt:'2026-10-06T01:00:00Z',transactionDate:'2026-10-06T01:00:00Z',amount:'1000',signedAmount:'1000',feeTaxAmount:'0',memo:null,dividend:null}];await page.clock.setFixedTime(new Date('2026-10-06T03:00:00Z'));await page.route('**/api/accounts/*/cash-overview*',r=>r.fulfill({json:{data:{account:{id:'a',currentBalance:'900'},monthly:{},yearly:{},recentTransactions:rows}}}));await page.route('**/api/accounts/*/cash-transactions*',r=>r.fulfill({json:{data:rows,meta:{total:2}}}));await page.goto('/detail/cash');await expect(page.getByRole('button',{name:'매수 내역 수정'})).toBeVisible();await expect(page.getByRole('button',{name:'입금 내역 수정'})).toHaveCount(0);await page.getByRole('button',{name:'매수 내역 수정'}).click();await page.getByRole('textbox',{name:'금액',exact:true}).fill('150');await page.getByRole('button',{name:'변경',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);expect(f.writes[0].path).toBe('/api/cash-transactions/2');expect(f.writes[0].method).toBe('PATCH');
});

test('journal whole-card swipe preserves heading and calendar swipe resets scroll',async({page})=>{
 await fixture(page);await page.goto('/journal?date=2026-09-18');const card=page.getByTestId('journal-day-card'),heading=page.getByTestId('journal-day-heading');await expect(card).toBeVisible();
 const swipe=async(target:typeof card)=>target.evaluate(el=>{const emit=(type:string,x:number)=>{const t=new Touch({identifier:1,target:el,clientX:x,clientY:100});el.dispatchEvent(new TouchEvent(type,{bubbles:true,touches:type==='touchend'?[]:[t],changedTouches:[t]}));};emit('touchstart',240);emit('touchmove',210);emit('touchmove',140);emit('touchend',140);});
 await swipe(card.getByText('일별손익 보기',{exact:false}));await expect(heading).toContainText('2026.09.19');await expect(page).not.toHaveURL(/view=profit/);const top=(await heading.boundingBox())!.y;await swipe(card);await expect(heading).toContainText('2026.09.20');expect(Math.abs((await heading.boundingBox())!.y-top)).toBeLessThan(2);
 const region=page.viewportSize()!.width>=600?page.locator('[data-scroll-region="journal-calendar"]'):page.locator('main');await region.evaluate(el=>el.scrollTop=80);const calendar=page.locator('[data-testid="journal-layout"] > div').first();await swipe(calendar);await expect.poll(()=>region.evaluate(el=>el.scrollTop)).toBe(0);
});
