import {test,expect,type Page} from '@playwright/test';
const sec=(id:string,name:string,price:string|null='519000',list='WATCHLIST')=>({id,symbol:id==='1'?'005380':id.padStart(6,'0'),name,marketType:'KOSPI',securityType:'COMMON',listType:list,watchlistItemId:id,currentPrice:price,previousClosePrice:price==='519000'?'454000':price,priceUpdatedAt:'2026-10-02T00:00:00Z',valuation:{metricDate:'2025-12-31',eps:'100',bps:'200',per:id==='3'?null:'10',pbr:'1',roe:'8',dividendPerShare:'100',dividendYield:'1',marketCap:null},memo:null,targetBuyPrice:null,priority:1});
const holding=(id:string,name:string,market:string|null,price:string|null='519000')=>({securityId:id,symbol:id==='1'?'005380':id.padStart(6,'0'),name,marketType:'KOSPI',quantity:'700',purchaseAmount:'161000000',averagePurchasePrice:'230000',currentPrice:price,previousClosePrice:'454000',marketValue:market,unrealizedProfitLoss:market?String(Number(market)-161000000):null,unrealizedReturnRate:market?'125.65':null,priceChangeRate:price?'14.3171806':null,priceUpdatedAt:'2026-10-02T00:00:00Z',marketStatus:'NORMAL'});
const trade=(id:string,type='SELL',sid='1',date='2026-09-18T03:00:00Z')=>({id,type,buyTradeId:sid==='1'?'lot1':'lot9',tradedAt:date,security:{id:sid,symbol:sid==='1'?'005380':'000009',name:sid==='1'?'현대자동차':'거래만종목',marketType:'KOSPI'},quantity:'70',unitPrice:type==='BUY'?'230000':'519000',amount:type==='BUY'?'16100000':'36330000',realizedProfitLoss:type==='BUY'?null:'20230000',memo:null});
const lot=(id:string,remaining='70',sid='1')=>({id,boughtAt:'2026-09-10T03:00:00Z',buyDate:'2026-09-10',holdingDays:22,currentPrice:'519000',returnRate:'125.65',profitLoss:'20230000',priceUpdatedAt:'2026-10-02T00:00:00Z',valuationStatus:'AVAILABLE',security:{id:sid,symbol:'005380',name:'현대자동차',marketType:'KOSPI'},quantity:'70',soldQuantity:String(70-Number(remaining)),remainingQuantity:remaining,unitPrice:'230000',remainingPurchaseAmount:String(Number(remaining)*230000),memo:null,sellTrades:[]});
async function fixture(page:Page){let fail=false;const writes:Array<{path:string;method:string;body:Record<string,string>}>=[];await page.route('**/api/**',async route=>{const url=new URL(route.request().url()),path=url.pathname,method=route.request().method();if(method!=='GET'){writes.push({path,method,body:route.request().postDataJSON()??{}});await new Promise(r=>setTimeout(r,150));return route.fulfill({status:fail?500:200,json:fail?{error:{message:'테스트 저장 실패'}}:{data:{id:'new',cashBalanceAdjusted:false}}});}
 if(path==='/api/accounts')return route.fulfill({json:{data:[{id:'a',name:'기본 계좌',brokerName:'증권',cashBalance:'203300000',isActive:true,isDefault:true}]}});
 const securities=[sec('1','현대자동차'),sec('2','삼성전자','76800'),sec('3','삼성미수집',null),sec('4','기아','149429','RECOMMENDED'),sec('9','거래만종목','1000')];
 if(path==='/api/securities'){const q=url.searchParams.get('query');return route.fulfill({json:{data:q?[sec('77','삼성신규','1000'),...securities.filter(s=>s.name.includes(q))]:securities}});}
 if(path.endsWith('/analysis'))return route.fulfill({json:{data:{security:securities[0],valuation:securities[0].valuation,previousValuation:null,fundamentals:null,statements:[]}}});
 if(path.endsWith('/holdings'))return route.fulfill({json:{data:[holding('1','현대자동차','363300000'),...Array.from({length:10},(_,i)=>holding(String(20+i),'보유'+i,String(200000000-i*1000))),holding('30','시세미수집',null,null)]}});
 if(path.endsWith('/trades')){const data=[trade('s1'),...Array.from({length:4},(_,i)=>trade('s2026-'+i)),trade('s2','SELL','1','2025-09-18T03:00:00Z'),...Array.from({length:4},(_,i)=>trade('s2025-'+i,'SELL','1','2025-09-18T03:00:00Z')),trade('s9','SELL','9')].filter(t=>!url.searchParams.has('securityId')||t.security.id===url.searchParams.get('securityId'));return route.fulfill({json:{data,summary:{buyAmount:'16100000',sellAmount:'36330000',realizedProfitLoss:'20230000'},daily:[]}});}
 if(path.endsWith('/buy-lots'))return route.fulfill({json:{data:[lot('lot1'),...Array.from({length:4},(_,i)=>lot('lot'+(i+2)))]}});
 if(path.endsWith('/dashboard'))return route.fulfill({json:{data:{account:{id:'a',name:'기본 계좌',brokerName:'증권'},cashBalance:'203300000',purchaseAmount:'161000000',stockValue:'363300000',totalAssetValue:'566600000',unrealizedProfitLoss:'202300000',unrealizedReturnRate:'125.65',pricingComplete:true,latestPriceUpdatedAt:'2026-10-02T00:00:00Z',holdings:[]}}});
 if(path.endsWith('/asset-history'))return route.fulfill({json:{data:[],summary:{profitLoss:null,returnRate:null}}});
 if(path.startsWith('/api/buy-trades/'))return route.fulfill({json:{data:{id:'lot1',type:'BUY',account:{id:'a',name:'기본 계좌'},security:securities[0],boughtAt:'2026-09-10T03:00:00Z',quantity:'70',soldQuantity:'0',remainingQuantity:'70',unitPrice:'230000',memo:'원본 매수',cashTransaction:{id:'c',feeTaxAmount:'0',balanceAfter:'203300000'},sellTrades:[]}}});
 if(path.startsWith('/api/sell-trades/'))return route.fulfill({json:{data:{id:'s1',type:'SELL',account:{id:'a',name:'기본 계좌'},security:securities[0],buyTradeId:'lot1',soldAt:'2026-09-18T03:00:00Z',quantity:'70',unitPrice:'519000',memo:'원본 매도',cashTransaction:{id:'c',feeTaxAmount:'0',balanceAfter:'203300000'}}}});
 return route.fulfill({status:404,json:{error:{message:'테스트 조회 실패'}}});});return {writes,fail:()=>{fail=true;},success:()=>{fail=false;}};}
async function selected(page:Page){await page.goto('/stocks?tab=holding');const tablet=page.viewportSize()!.width>=600;if(tablet)await page.getByRole('row',{name:'현대자동차 상세보기'}).click();else await page.getByRole('button',{name:'현대자동차 상세보기',exact:true}).click();await expect(page.getByTestId('lot-lot1')).toBeVisible();}
const screenshot=async(page:Page,name:string,project:string)=>page.screenshot({path:`test-results/targets/stocks-${name}-${project}.png`});
test('layout, four tabs, independent scrolling, title and centered value popup',async({page},info)=>{await fixture(page);await page.goto('/stocks');await expect(page.getByRole('tab',{name:'거래종목',exact:true})).toBeVisible();expect(await page.locator('main').evaluate(n=>{const s=getComputedStyle(n);return[s.paddingTop,s.paddingLeft,s.paddingRight];})).toEqual(['0px','8px','8px']);expect((await page.locator('header').boundingBox())!.height).toBe(44);await screenshot(page,'list',info.project.name);await selected(page);const tablet=page.viewportSize()!.width>=600;if(tablet){await expect(page.getByRole('heading',{name:'종목목록(보유종목)'})).toBeVisible();await expect(page.getByRole('tab',{name:'관심종목',exact:true})).toHaveCount(0);const left=page.getByTestId('stock-left'),right=page.getByTestId('stock-right'),a=await left.boundingBox(),b=await right.boundingBox();expect(b!.x-a!.x-a!.width).toBeCloseTo(16,1);expect(a!.width).toBeCloseTo(b!.width,1);for(const column of[left,right])expect(await column.evaluate(n=>{const s=getComputedStyle(n);return[s.paddingLeft,s.paddingRight];})).toEqual(['0px','0px']);await left.evaluate(n=>n.scrollTop=80);await right.evaluate(n=>n.scrollTop=100);expect(await left.evaluate(n=>n.scrollTop)).toBe(80);expect(await page.locator('main').evaluate(n=>n.scrollTop)).toBe(0);await right.evaluate(n=>n.scrollTop=0);await left.evaluate(n=>n.scrollTop=0);}await screenshot(page,'detail',info.project.name);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const img of await page.locator('img[src^="/stocks-v03/"]:visible').all()){const geometry=await img.evaluate((n:HTMLImageElement)=>({natural:n.naturalWidth,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height,name:n.getAttribute('src')}));expect(geometry.natural,geometry.name!).toBeGreaterThan(0);expect(geometry.width,geometry.name!).toBeGreaterThan(0);expect(geometry.width/geometry.height,geometry.name!).toBeGreaterThanOrEqual(0.99);expect(geometry.width/geometry.height,geometry.name!).toBeLessThan(1.1);}if(tablet){await page.getByRole('button',{name:'현대자동차 즐겨찾기 추가'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'현대자동차 가치지표',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();const r=await dialog.boundingBox(),v=page.viewportSize()!;expect(r!.x+r!.width/2).toBeCloseTo(v.width/2,0);expect(r!.y+r!.height/2).toBeCloseTo(v.height/2,0);} });
test('tab sorting has independent direction, missing metrics last and traded classification',async({page},info)=>{await fixture(page);await page.goto('/stocks?tab=watchlist');await expect(page.getByRole('combobox',{name:'정렬 기준'})).toContainText('종목명');await page.getByRole('combobox',{name:'정렬 기준'}).click();await page.getByRole('option',{name:'PER',exact:true}).click();await page.getByRole('button',{name:/오름차순 · 내림차순/}).click();const names=page.viewportSize()!.width>=600?page.getByRole('row').filter({has:page.getByRole('button',{name:/가치지표/})}):page.locator('[data-testid^="stock-card-"]');await expect(names).toHaveCount(2);expect(await names.last().innerText()).toContain('삼성미수집');await page.getByRole('tab',{name:'거래종목',exact:true}).click();await expect(page.getByRole('combobox',{name:'정렬 기준'})).toContainText('마지막 매도일');await expect(page.getByRole('button',{name:'거래만종목 가치지표'})).toBeVisible();await expect(page.getByRole('button',{name:'현대자동차 가치지표'})).toHaveCount(0);await screenshot(page,'traded',info.project.name);});
test('search popup uses cover content, 52px rows, highlight, IME and duplicate guard',async({page},info)=>{const f=await fixture(page);await page.goto('/stocks');await page.getByRole('button',{name:'종목 추가',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();const search=dialog.getByRole('textbox',{name:'전체 종목 검색'});await expect(search).toBeFocused();await search.fill('삼성');await search.press('Enter');const rows=dialog.getByTestId('security-search-result');await expect(rows).toHaveCount(3);expect((await rows.first().boundingBox())!.height).toBe(52);expect(await rows.first().locator('span').first().evaluate(n=>getComputedStyle(n).color)).toBe('rgb(250, 97, 112)');await expect(rows.nth(1).getByRole('button')).toBeDisabled();await screenshot(page,'search',info.project.name);await rows.first().getByRole('button',{name:'+ 추가'}).click();const category=page.getByRole('dialog').last();await category.getByRole('button',{name:'관심종목',exact:true}).click();f.fail();await category.getByRole('button',{name:'등록',exact:true}).click();await expect(category.getByRole('alert')).toContainText('테스트 저장 실패');f.success();await category.getByRole('button',{name:'등록',exact:true}).dblclick();await expect(page).toHaveURL(/tab=watchlist/);expect(f.writes.filter(w=>w.path.endsWith('/watchlist-items'))).toHaveLength(2);});
test('Lot price evaluation, sell popup paired fields, cash math, validation and failure preserve',async({page},info)=>{const f=await fixture(page);await selected(page);const lot=page.getByTestId('lot-lot1');await expect(lot).toContainText('36,330,000원');await expect(lot).toContainText('20,230,000원');await lot.getByRole('button',{name:'2026-09-10 Lot 매도'}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();const q=dialog.getByRole('textbox',{name:'매도수량',exact:true}),p=dialog.getByRole('textbox',{name:'매도가격',exact:true});await expect(q).toHaveValue('70');await expect(dialog.getByLabel('매도일자',{exact:true})).toBeFocused();await dialog.getByLabel('매도일자',{exact:true}).press('Enter');await expect(q).toBeFocused();await expect(dialog.getByRole('textbox',{name:'매수가격',exact:true})).toHaveValue('230,000');await expect(dialog).toContainText('239,630,000원');expect(Math.abs((await q.boundingBox())!.x-(await p.boundingBox())!.x)).toBeLessThan(1);await q.fill('71');await expect(dialog.getByRole('button',{name:'매도',exact:true})).toBeDisabled();await q.fill('70');await q.press('Enter');await expect(p).toBeFocused();await p.press('Enter');const memo=dialog.getByRole('textbox',{name:'메모',exact:true});await expect(memo).toBeFocused();await memo.fill('테스트 메모');await memo.dispatchEvent('keydown',{key:'Enter',isComposing:true});expect(f.writes).toHaveLength(0);f.fail();await dialog.getByRole('button',{name:'매도',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('테스트 저장 실패');await expect(q).toHaveValue('70');const body=page.getByTestId('stock-flow-modal-body');await dialog.getByRole('button',{name:'취소',exact:true}).scrollIntoViewIfNeeded();await expect(dialog.getByRole('button',{name:'취소',exact:true})).toBeInViewport();await screenshot(page,'sell',info.project.name);expect(await body.evaluate(n=>n.scrollHeight>=n.clientHeight)).toBe(true);f.success();await dialog.getByRole('button',{name:'매도',exact:true}).dblclick();await expect(dialog).toHaveCount(0);expect(f.writes.filter(w=>w.path==='/api/sell-trades')).toHaveLength(2);});
test('buy edit replaces original average, current cash unchanged; year sticky and sell actions isolated',async({page},info)=>{const f=await fixture(page);await selected(page);await page.getByRole('button',{name:'lot1 매수 수정'}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();const price=dialog.getByRole('textbox',{name:'매수가격',exact:true});await price.fill('240000');await expect(dialog.getByTestId('average-comparison')).toContainText('변경 후 231,000원');await expect(dialog).toContainText('현재 예수금');await expect(dialog).toContainText('203,300,000원');await expect(dialog).not.toContainText('거래 후 예수금');await screenshot(page,'buy-edit',info.project.name);await dialog.getByRole('button',{name:'변경',exact:true}).click();await expect(dialog).toHaveCount(0);expect(f.writes[0].method).toBe('PATCH');expect(f.writes[0].path).toBe('/api/buy-trades/lot1');await page.getByRole('tab',{name:'거래내역',exact:true}).click();const year=page.getByTestId('trade-year-title').first();await expect(year).toBeVisible();expect(await year.evaluate(n=>getComputedStyle(n).position)).toBe('sticky');const scroll=page.viewportSize()!.width>=600?page.getByTestId('stock-right'):page.locator('main');await scroll.evaluate(n=>n.scrollTop=130);const top=(await scroll.boundingBox())!.y;expect((await year.boundingBox())!.y).toBeCloseTo(top,0);await scroll.evaluate(n=>{const next=n.querySelector('[data-testid="trade-year-2025"]')!;n.scrollTop+=next.getBoundingClientRect().top-n.getBoundingClientRect().top;});expect((await page.getByTestId('trade-year-2025').getByTestId('trade-year-title').boundingBox())!.y).toBeCloseTo(top,0);await scroll.evaluate(n=>n.scrollTop=0);await page.getByRole('button',{name:'s1 매도 수정'}).click();await expect(page.getByRole('dialog')).toContainText('매도 수정');await page.getByRole('dialog').getByRole('button',{name:'취소',exact:true}).click();await page.getByRole('button',{name:'s1 매도 삭제'}).click();const remove=page.getByRole('dialog');await expect(remove).toContainText('예수금은 자동 변경되지 않습니다.');await remove.getByRole('button',{name:'취소',exact:true}).click();expect(f.writes).toHaveLength(1);});

test('QA account switch clears previous holding detail; empty and fetch error differ',async({page},info)=>{
 await fixture(page);
 await page.route('**/api/accounts',r=>r.fulfill({json:{data:[{id:'a',name:'기본 계좌',cashBalance:'203300000',isActive:true,isDefault:true},{id:'b',name:'빈 계좌',cashBalance:'0',isActive:true,isDefault:false}]}}));
 let error=false;
 await page.route('**/api/accounts/b/**',r=>r.fulfill(error?{status:500,json:{error:{message:'QA 조회 실패'}}}:{json:{data:[],summary:{buyAmount:'0',sellAmount:'0',realizedProfitLoss:'0'}}}));
 await selected(page);
 await page.evaluate(()=>{localStorage.setItem('roxstock-selected-account-id','b');window.dispatchEvent(new Event('roxstock-selected-account'));});
 if(page.viewportSize()!.width>=600) await expect(page.getByTestId('stock-right')).toHaveCount(0);
 else await page.goto('/stocks');
 await expect(page.getByText('내용이 없습니다.').first()).toBeVisible();
 await expect(page.getByRole('button',{name:'현대자동차 가치지표',exact:true})).toHaveCount(0);
 await screenshot(page,'qa-empty-account',info.project.name);
 error=true;await page.reload();await expect(page.getByRole('alert').first()).toBeVisible({timeout:15000});
 await screenshot(page,'qa-fetch-error',info.project.name);
});
test('QA price popup rejects empty, preserves failed value and prevents duplicate price writes',async({page},info)=>{
 const f=await fixture(page);await selected(page);await page.getByRole('button',{name:/65,000원.*14.3/}).last().click();
 const d=page.getByRole('dialog'),input=d.getByRole('textbox',{name:'변경할 현재가',exact:true});
 await expect(d).toBeVisible();await input.fill('');await expect(d.getByRole('button',{name:'변경',exact:true})).toBeDisabled();
 await input.fill('520000');f.fail();await d.getByRole('button',{name:'변경',exact:true}).click();await expect(d.getByRole('alert')).toContainText('테스트 저장 실패');await expect(input).toHaveValue('520,000');await screenshot(page,'qa-price-failure',info.project.name);
 f.success();await d.getByRole('button',{name:'변경',exact:true}).dblclick();await expect(d).toHaveCount(0);expect(f.writes.filter(w=>w.path.includes('/price'))).toHaveLength(2);
});
