import {expect,type Page} from '@playwright/test';
const sec=(id:string,name:string,price:string|null='519000',list='WATCHLIST')=>({id,symbol:id==='1'?'005380':id.padStart(6,'0'),name,marketType:'KOSPI',securityType:'COMMON',listType:list,watchlistItemId:id,currentPrice:price,previousClosePrice:price==='519000'?'454000':price,priceUpdatedAt:'2026-10-02T00:00:00Z',valuation:{metricDate:'2025-12-31',eps:'100',bps:'200',per:id==='3'?null:'10',pbr:'1',roe:'8',dividendPerShare:'100',dividendYield:'1',marketCap:null},memo:null,targetBuyPrice:null,priority:1});
const holding=(id:string,name:string,market:string|null,price:string|null='519000')=>({securityId:id,symbol:id==='1'?'005380':id.padStart(6,'0'),name,marketType:'KOSPI',quantity:'700',purchaseAmount:'161000000',averagePurchasePrice:'230000',currentPrice:price,previousClosePrice:'454000',marketValue:market,unrealizedProfitLoss:market?String(Number(market)-161000000):null,unrealizedReturnRate:market?'125.65':null,priceChangeRate:price?'14.3171806':null,priceUpdatedAt:'2026-10-02T00:00:00Z',marketStatus:'NORMAL'});
const trade=(id:string,type='SELL',sid='1',date='2026-09-18T03:00:00Z')=>({id,type,buyTradeId:sid==='1'?'lot1':'lot9',tradedAt:date,security:{id:sid,symbol:sid==='1'?'005380':'000009',name:sid==='1'?'현대자동차':'거래만종목',marketType:'KOSPI'},quantity:'70',unitPrice:type==='BUY'?'230000':'519000',amount:type==='BUY'?'16100000':'36330000',realizedProfitLoss:type==='BUY'?null:'20230000',memo:null});
const lot=(id:string,remaining='70',sid='1')=>({id,boughtAt:'2026-09-10T03:00:00Z',buyDate:'2026-09-10',holdingDays:22,currentPrice:'519000',returnRate:'125.65',profitLoss:'20230000',priceUpdatedAt:'2026-10-02T00:00:00Z',valuationStatus:'AVAILABLE',security:{id:sid,symbol:'005380',name:'현대자동차',marketType:'KOSPI'},quantity:'70',soldQuantity:String(70-Number(remaining)),remainingQuantity:remaining,unitPrice:'230000',remainingPurchaseAmount:String(Number(remaining)*230000),memo:null,sellTrades:[]});
export async function fixture(page:Page){let fail=false,currentPrice='519000';const reads:string[]=[];const writes:Array<{path:string;method:string;body:Record<string,string>}>=[];await page.route('**/api/**',async route=>{const url=new URL(route.request().url()),path=url.pathname,method=route.request().method();if(method!=='GET'){writes.push({path,method,body:route.request().postDataJSON()??{}});await new Promise(r=>setTimeout(r,150));if(!fail&&path==='/api/securities/1/price')currentPrice=String(writes.at(-1)!.body.currentPrice);return route.fulfill({status:fail?500:200,json:fail?{error:{message:'테스트 저장 실패'}}:{data:{id:'new',cashBalanceAdjusted:false}}});}
 reads.push(path);
 if(path==='/api/accounts')return route.fulfill({json:{data:[{id:'a',name:'기본 계좌',brokerName:'증권',cashBalance:'203300000',isActive:true,isDefault:true}]}});
 const securities=[sec('1','현대자동차',currentPrice),sec('2','삼성전자','76800'),sec('3','삼성미수집',null),sec('4','기아','149429','RECOMMENDED'),sec('9','거래만종목','1000')];
 if(path==='/api/securities'){const q=url.searchParams.get('query');return route.fulfill({json:{data:q?[sec('77','삼성신규','1000'),...securities.filter(s=>s.name.includes(q))]:securities}});}
 if(path.endsWith('/analysis'))return route.fulfill({json:{data:{security:securities[0],valuation:securities[0].valuation,previousValuation:null,fundamentals:null,statements:[]}}});
 if(path.endsWith('/holdings'))return route.fulfill({json:{data:[holding('1','현대자동차',String(700*Number(currentPrice)),currentPrice),...Array.from({length:10},(_,i)=>holding(String(20+i),'보유'+i,String(200000000-i*1000))),holding('30','시세미수집',null,null)]}});
 if(path.endsWith('/trades')){const data=[trade('s1'),...Array.from({length:4},(_,i)=>trade('s2026-'+i)),trade('s2','SELL','1','2025-09-18T03:00:00Z'),...Array.from({length:4},(_,i)=>trade('s2025-'+i,'SELL','1','2025-09-18T03:00:00Z')),trade('s9','SELL','9')].filter(t=>!url.searchParams.has('securityId')||t.security.id===url.searchParams.get('securityId'));return route.fulfill({json:{data,summary:{buyAmount:'16100000',sellAmount:'36330000',realizedProfitLoss:'20230000'},daily:[]}});}
 if(path.endsWith('/buy-lots'))return route.fulfill({json:{data:[lot('lot1'),...Array.from({length:4},(_,i)=>lot('lot'+(i+2)))]}});
 if(path.endsWith('/dashboard'))return route.fulfill({json:{data:{account:{id:'a',name:'기본 계좌',brokerName:'증권'},cashBalance:'203300000',purchaseAmount:'161000000',stockValue:'363300000',totalAssetValue:'566600000',unrealizedProfitLoss:'202300000',unrealizedReturnRate:'125.65',pricingComplete:true,latestPriceUpdatedAt:'2026-10-02T00:00:00Z',holdings:[]}}});
 if(path.endsWith('/asset-history'))return route.fulfill({json:{data:[],summary:{profitLoss:null,returnRate:null}}});
 if(path.startsWith('/api/buy-trades/'))return route.fulfill({json:{data:{id:'lot1',type:'BUY',account:{id:'a',name:'기본 계좌'},security:securities[0],boughtAt:'2026-09-10T03:00:00Z',quantity:'70',soldQuantity:'0',remainingQuantity:'70',unitPrice:'230000',memo:'원본 매수',cashTransaction:{id:'c',feeTaxAmount:'0',balanceAfter:'203300000'},sellTrades:[]}}});
 if(path.startsWith('/api/sell-trades/'))return route.fulfill({json:{data:{id:'s1',type:'SELL',account:{id:'a',name:'기본 계좌'},security:securities[0],buyTradeId:'lot1',soldAt:'2026-09-18T03:00:00Z',quantity:'70',unitPrice:'519000',memo:'원본 매도',cashTransaction:{id:'c',feeTaxAmount:'0',balanceAfter:'203300000'}}}});
 return route.fulfill({status:404,json:{error:{message:'테스트 조회 실패'}}});});return {writes,reads,fail:()=>{fail=true;},success:()=>{fail=false;}};}
export async function selected(page:Page){await page.goto('/stocks?tab=holding');const tablet=page.viewportSize()!.width>=600;if(tablet)await page.getByRole('row',{name:'현대자동차 상세보기'}).click();else await page.getByRole('button',{name:'현대자동차 상세보기',exact:true}).click();await expect(page.getByTestId('lot-lot1')).toBeVisible();}
export const screenshot=async(page:Page,name:string,project:string)=>page.screenshot({path:`test-results/targets/stocks-${name}-${project}.png`});
