import {expect,test} from '@playwright/test';
test('compound colors, card actions, year calendar and formatted numeric input',async({page},info)=>{
 const goal={id:'1',goalName:'기준형',displayColor:'#5EA1F0',annualTargetRate:'10',isDefault:true,isVisible:true,rows:[],yearTarget:'1000000',finalTarget:'2000000',progress:'50'};
 const plan={id:'1',planName:'테스트 계획',displayColor:'#FA616E',startYear:2025,endYear:2027,duration:3,initialAssetValue:'1000000',annualContributionAmount:'100000',goals:[goal],status:'ACTIVE'};
 await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;await route.fulfill({json:{data:path==='/api/accounts'?[{id:'1',name:'기본',isActive:true,isDefault:true}]:path.includes('/compound-plans')?{accountId:'1',plans:[plan],currentAssets:'1000000',currentYear:2026,pricingComplete:true,asOf:'2026-10-06T00:00:00Z'}:[]}});});
 await page.goto('/detail/compound');const card=page.getByTestId('compound-plan-1');await expect(card).toHaveCSS('border-top-color','rgb(255, 255, 255)');await expect(page.getByTestId('header-add')).toHaveCSS('width','32px');
 if(info.project.name==='cover')await expect(page.getByLabel('계획 선택')).toHaveCount(0);if(info.project.name==='tablet')await expect(page.getByRole('radio')).toHaveAttribute('aria-checked','true');await page.screenshot({path:info.outputPath('compound-list.png')});
 await card.getByRole('button',{name:'테스트 계획 수정'}).click();await expect(page.getByLabel('계획명',{exact:true})).toHaveValue('테스트 계획');await page.getByLabel('시작 금액',{exact:true}).fill('1000000');await expect(page.getByLabel('시작 금액',{exact:true})).toHaveValue('1,000,000');await page.getByLabel('종료 연도',{exact:true}).click();await expect(page.getByRole('button',{name:'2024',exact:true})).toBeDisabled();await page.getByRole('button',{name:'2027',exact:true}).click();await page.screenshot({path:info.outputPath('compound-form.png')});
});
test('value header, large money and whole issued-shares row bold',async({page},info)=>{
 const row={id:'1',name:'삼성전자',symbol:'005930',currentPrice:'70000',previousClosePrice:'69000',priceUpdatedAt:'2026-10-06T00:00:00Z',w:'1.2',per:'12',pbr:'1.2',roe:'10'};
 await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;let data:any=[];if(path==='/api/accounts')data=[{id:'1',name:'기본',isActive:true,isDefault:true}];if(path==='/api/value-analysis')data={rows:[row],total:1,year:2026,query:''};if(path==='/api/value-analysis/1')data={security:row,year:2026,valuation:{bps:'50000',eps:'3000',roe:'10',per:'12',pbr:'1.2',metricDate:'2026-10-06'},issuedShares:'10000000',w:'1.2',fairPrices:['0.7','0.8','0.9','1.0'].map(persistence=>({persistence,price:'90000'})),requiredReturn:'8',equity:'1000000000000',closingDate:'2025-12-31',rows:[],mode:'annual',startYear:2024,startQuarter:null,count:3,notices:[]};await route.fulfill({json:{data}});});
 await page.goto('/detail/value?view=detail&selected=1');await expect(page.getByTestId('value-detail')).toContainText('1조원');await expect(page.getByTestId('value-issued-shares')).toHaveCSS('font-weight','700');if(info.project.name==='cover'){const title=await page.getByRole('heading',{level:1}).boundingBox(),code=await page.getByText('005930',{exact:true}).last().boundingBox();expect(title!.y+title!.height).toBeLessThanOrEqual(code!.y);}await page.screenshot({path:info.outputPath('value-detail.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('stored financial list and three-period detail, no automatic collection, cover/tablet',async({page},info)=>{
 let writes=0;const values={revenue:'100000000',operatingProfit:'20000000',netIncome:'10000000',parentNetIncome:null,totalAssets:'500000000',totalLiabilities:'0',totalEquity:'500000000',parentEquity:null,operatingCashFlow:'0',investingCashFlow:null,financingCashFlow:null,cashEquivalents:'10000000'};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());if(u.pathname.endsWith('/financial-refresh/active'))return route.fulfill({json:{data:null}});if(route.request().method()!=='GET')writes++;let data:any=[];
 if(u.pathname==='/api/accounts')data=[{id:'1',name:'기본',isDefault:true,isActive:true}];
 if(u.pathname==='/api/financial-statements')data={year:2026,market:'KOSPI',total:1,rows:[{id:'1',name:'삼성전자',symbol:'005930',market:'KOSPI',currentPrice:'70000',previousClosePrice:'69000',priceUpdatedAt:'2026-10-06T00:00:00Z',targetPrice:'90000',w:'1.28',value:'1.28',eps:'5000',epsYield:'7.14',roe:'12',issuedShares:'10000000',capital:'1000000000000',netIncome:'100000000000'}]};
 if(u.pathname==='/api/financial-statements/1')data={security:{id:'1',name:'삼성전자',symbol:'005930'},collectedAt:null,notices:[],rows:[0,1,2].map(i=>({key:'2024:'+i,label:'202'+(4+i),year:2024+i,quarter:null,values,growth:Object.fromEntries(Object.keys(values).map(k=>[k,null])),basis:'CFS',collectedAt:null,isDerived:false}))};
 await route.fulfill({json:{data}});});
 await page.goto('/detail/financials');await expect(page.getByRole('button',{name:/삼성전자/})).toBeVisible();await page.screenshot({path:info.outputPath('financial-list.png')});await page.getByRole('button',{name:/삼성전자/}).click();await expect(page.getByRole('table')).toHaveCount(3);await expect(page.getByLabel('재무제표 시작분기')).toBeDisabled();await page.getByRole('button',{name:'분기',exact:true}).click();await expect(page.getByLabel('재무제표 시작분기')).toBeEnabled();await page.screenshot({path:info.outputPath('financial-detail.png')});expect(writes).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
